const snapshot = (points: number, comments: number) => ({
  points,
  comments,
  capturedAt: "2026-07-22",
});

/**
 * User-supplied high-engagement HN discovery batch. These are lightweight Desk
 * leads only. `hnSnapshot` preserves the supplied discovery context; it is not
 * a source grade and does not authorize use of any comment as evidence.
 */
export const chinaHn300Leads = [
  {
    id: "lead-2022-nyt-russia-olympics-delay",
    title:
      "China asked Russia to delay war until after Olympics, Biden officials say",
    url: "https://www.nytimes.com/2022/03/02/us/politics/russia-ukraine-china.html",
    publisher: "The New York Times",
    accessedAt: "2026-07-22",
    publishedAt: "2022-03-02",
    contentType: "reporting",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["russia", "ukraine", "diplomacy", "intelligence"],
    evidenceStatus: "unverified",
    paywall: true,
    hnStoryId: "30532935",
    hnSnapshot: snapshot(344, 304),
    notes:
      "Anonymous US-official attribution is a reporting lead, not proof that Beijing made the request; compare later intelligence assessments and Chinese and Russian responses before use.",
  },
  {
    id: "lead-2023-yomiuri-rare-earth-magnet-tech",
    title: "China plans to ban exports of rare earth magnet tech",
    url: "https://japannews.yomiuri.co.jp/world/asia-pacific/20230405-101753/",
    publisher: "The Japan News / Yomiuri Shimbun",
    accessedAt: "2026-07-22",
    publishedAt: "2023-04-05",
    contentType: "reporting",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["rare-earths", "magnets", "export-controls", "industrial-policy"],
    evidenceStatus: "unverified",
    hnStoryId: "35456721",
    hnSnapshot: snapshot(342, 588),
    notes:
      "A reported policy plan is not an enacted ban. Resolve the Chinese catalogue or ministry record, covered technology, effective status, and later revisions.",
  },
  {
    id: "lead-2018-engadget-xinjiang-surveillance",
    title: "China's Xinjiang surveillance is the dystopian future nobody wants",
    url: "https://www.engadget.com/2018/02/22/china-xinjiang-surveillance-tech-spread/",
    publisher: "Engadget",
    accessedAt: "2026-07-22",
    publishedAt: "2018-02-22",
    contentType: "reporting",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["xinjiang", "surveillance", "biometrics", "human-rights"],
    evidenceStatus: "unverified",
    hnStoryId: "16441347",
    hnSnapshot: snapshot(342, 261),
    notes:
      "Dated secondary overview with broad framing. Trace technical and human-rights assertions to field reporting, procurement records, and primary policy documents; do not extrapolate unchanged conditions to the present.",
  },
  {
    id: "lead-2025-scmp-thorium-uranium",
    title: "China reaches energy milestone by ‘breeding’ uranium from thorium",
    url: "https://www.scmp.com/news/china/science/article/3331312/china-reaches-energy-independence-milestone-breeding-uranium-thorium",
    publisher: "South China Morning Post",
    accessedAt: "2026-07-22",
    publicationYear: 2025,
    contentType: "reporting",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["thorium", "nuclear-energy", "molten-salt-reactor", "science"],
    evidenceStatus: "unverified",
    paywall: true,
    archiveUrl: "https://archive.is/DQpXM",
    hnStoryId: "46016639",
    hnSnapshot: snapshot(341, 314),
    notes:
      "Archive supplied. Resolve the incomplete Science and Technology Daily English URL and underlying technical record; distinguish experimental uranium production from fuel-cycle scale or energy independence.",
  },
  {
    id: "lead-2019-pandaily-amazon-china-market",
    title: "Amazon Quits China Market",
    url: "https://pandaily.com/amazon-quits-china-market-another-u-s-e-commerce-giant-failing-in-china/",
    publisher: "Pandaily",
    accessedAt: "2026-07-22",
    publicationYear: 2019,
    contentType: "reporting",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["amazon", "e-commerce", "market-exit", "platforms"],
    evidenceStatus: "unverified",
    hnStoryId: "19717991",
    hnSnapshot: snapshot(339, 295),
    notes:
      "The headline may collapse distinct businesses. Verify which domestic marketplace services ended and which cross-border, cloud, device, or seller operations continued.",
  },
  {
    id: "lead-2019-bloomberg-electric-buses-oil-demand",
    title: "China's e-buses dent oil demand more than electric cars do",
    url: "https://www.bloomberg.com/news/articles/2019-03-19/forget-tesla-it-s-china-s-e-buses-that-are-denting-oil-demand",
    publisher: "Bloomberg",
    accessedAt: "2026-07-22",
    publishedAt: "2019-03-19",
    contentType: "reporting",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["electric-buses", "oil-demand", "transport", "energy-transition"],
    evidenceStatus: "unverified",
    paywall: true,
    hnStoryId: "19438252",
    hnSnapshot: snapshot(339, 257),
    notes:
      "Treat avoided-oil estimates as model outputs, not directly observed demand. Capture fleet, utilization, displacement, geography, and counterfactual assumptions.",
  },
  {
    id: "lead-2020-npr-charles-lieber-arrest",
    title:
      "Harvard scientist is arrested, accused of lying about ties to China",
    url: "https://www.npr.org/2020/01/28/800442646/acclaimed-harvard-scientist-is-arrested-accused-of-lying-about-ties-to-china",
    publisher: "NPR",
    accessedAt: "2026-07-22",
    publishedAt: "2020-01-28",
    contentType: "reporting",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: [
      "research-security",
      "charles-lieber",
      "universities",
      "criminal-case",
    ],
    evidenceStatus: "unverified",
    hnStoryId: "22176261",
    hnSnapshot: snapshot(338, 191),
    notes:
      "An arrest report is an early procedural snapshot. Any use must incorporate the charging documents, later verdict and sentencing record, and the distinction between disclosure offenses and espionage.",
  },
  {
    id: "lead-2018-bloomberg-ip-theft-punishments",
    title: "China Announces Punishments for Intellectual-Property Theft",
    url: "https://www.bloomberg.com/news/articles/2018-12-04/china-announces-new-punishments-for-intellectual-property-theft",
    publisher: "Bloomberg",
    accessedAt: "2026-07-22",
    publishedAt: "2018-12-04",
    contentType: "reporting",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["intellectual-property", "enforcement", "trade", "regulation"],
    evidenceStatus: "unverified",
    paywall: true,
    hnStoryId: "18602843",
    hnSnapshot: snapshot(337, 199),
    notes:
      "Announcement and implementation are separate states. Resolve the controlling Chinese record and later enforcement evidence before evaluating effectiveness.",
  },
  {
    id: "lead-2021-bbc-uyghur-genocide-legal-opinion",
    title: "Uighurs: ‘Credible case’ China carrying out genocide",
    url: "https://www.bbc.com/news/uk-55973215",
    publisher: "BBC News",
    accessedAt: "2026-07-22",
    publicationYear: 2021,
    contentType: "reporting",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["uyghurs", "xinjiang", "genocide", "legal-analysis"],
    evidenceStatus: "unverified",
    hnStoryId: "26217821",
    hnSnapshot: snapshot(336, 288),
    notes:
      "Preserve the difference between a commissioned legal opinion, parliamentary or executive determinations, and a judgment by a competent court; review the opinion and cited evidence directly.",
  },
  {
    id: "lead-2020-wikimedia-wipo-accreditation",
    title: "China blocks Wikimedia Foundation’s accreditation to WIPO",
    url: "https://wikimediafoundation.org/news/2020/09/24/china-blocks-wikimedia-foundations-accreditation/",
    publisher: "Wikimedia Foundation",
    accessedAt: "2026-07-22",
    publishedAt: "2020-09-24",
    contentType: "primary",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["wikimedia", "wipo", "accreditation", "internet-governance"],
    evidenceStatus: "unverified",
    hnStoryId: "24588913",
    hnSnapshot: snapshot(335, 147),
    notes:
      "Primary for Wikimedia's account and position, not a neutral adjudication. Pair with WIPO meeting records and China's stated objection.",
  },
  {
    id: "lead-2023-cnbc-evergrande-chapter-15",
    title:
      "China’s property giant Evergrande files for bankruptcy protection in Manhattan",
    url: "https://www.cnbc.com/2023/08/18/china-property-developer-evergrande-files-for-bankruptcy-protection-in-us.html",
    publisher: "CNBC",
    accessedAt: "2026-07-22",
    publishedAt: "2023-08-18",
    contentType: "reporting",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["evergrande", "property", "chapter-15", "debt"],
    evidenceStatus: "unverified",
    hnStoryId: "37171187",
    hnSnapshot: snapshot(334, 382),
    notes:
      "Describe the US filing precisely as Chapter 15 recognition/protection rather than generic bankruptcy, and incorporate later Hong Kong liquidation developments if published.",
  },
  {
    id: "lead-2019-ieee-cotton-leaves-moon",
    title: "China Grew Two Cotton Leaves on the Moon",
    url: "https://spectrum.ieee.org/tech-talk/aerospace/robotic-exploration/china-grew-these-leaves-on-the-moon",
    publisher: "IEEE Spectrum",
    accessedAt: "2026-07-22",
    publicationYear: 2019,
    contentType: "reporting",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["change-4", "moon", "cotton", "space-science"],
    evidenceStatus: "unverified",
    hnStoryId: "21116303",
    hnSnapshot: snapshot(331, 129),
    notes:
      "Keep germination, leaf growth, survival duration, and the sealed payload environment distinct; avoid implying sustained agriculture on the lunar surface.",
  },
  {
    id: "lead-2016-eff-cisco-human-rights-case",
    title:
      "Cisco Must Be Held Accountable for Aiding China’s Human Rights Abuses",
    url: "https://www.eff.org/press/releases/eff-court-cisco-must-be-held-accountable-aiding-chinas-human-rights-abuses",
    publisher: "Electronic Frontier Foundation",
    accessedAt: "2026-07-22",
    publicationYear: 2016,
    contentType: "analysis",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["cisco", "golden-shield", "human-rights", "litigation"],
    evidenceStatus: "unverified",
    hnStoryId: "10890907",
    hnSnapshot: snapshot(331, 116),
    notes:
      "Advocacy statement from a litigating position. Use for EFF's argument only; resolve complaints, decisions, appellate history, and disputed factual allegations from court records.",
  },
  {
    id: "lead-2019-npr-businesses-cyber-espionage",
    title: "As China Hacked, U.S. Businesses Turned a Blind Eye",
    url: "https://www.npr.org/2019/04/12/711779130/as-china-hacked-u-s-businesses-turned-a-blind-eye",
    publisher: "NPR",
    accessedAt: "2026-07-22",
    publishedAt: "2019-04-12",
    contentType: "reporting",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["cyber-espionage", "business", "attribution", "trade-secrets"],
    evidenceStatus: "unverified",
    hnStoryId: "19649409",
    hnSnapshot: snapshot(330, 195),
    notes:
      "Separate attributed intrusions, corporate response incentives, and the author's broader thesis; verify named incidents against indictments, technical reports, and company records.",
  },
  {
    id: "lead-2020-guardian-coronavirus-research-controls",
    title: "China clamping down on coronavirus research, deleted pages suggest",
    url: "https://www.theguardian.com/world/2020/apr/11/china-clamping-down-on-coronavirus-research-deleted-pages-suggest",
    publisher: "The Guardian",
    accessedAt: "2026-07-22",
    publishedAt: "2020-04-11",
    contentType: "reporting",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["covid-19", "research-policy", "deleted-pages", "censorship"],
    evidenceStatus: "unverified",
    hnStoryId: "22849747",
    hnSnapshot: snapshot(329, 331),
    notes:
      "Archived institutional notices can support a policy-change chronology; they do not decide virus-origin claims. Preserve deletion evidence, dates, and later policy records.",
  },
  {
    id: "lead-2019-usa-today-china-exit-bans",
    title:
      "China is increasingly using exit bans to bar Americans from leaving",
    url: "https://www.usatoday.com/story/news/world/2019/09/14/china-increasingly-using-exit-bans-bar-americans-leaving/2269191001/",
    publisher: "USA Today",
    accessedAt: "2026-07-22",
    publishedAt: "2019-09-14",
    contentType: "reporting",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["exit-bans", "consular-affairs", "law", "americans-in-china"],
    evidenceStatus: "unverified",
    hnStoryId: "20977342",
    hnSnapshot: snapshot(329, 245),
    notes:
      "Reported cases and travel-risk guidance need a denominator and legal context; distinguish criminal, civil, national-security, and coercive-leverage rationales.",
  },
  {
    id: "lead-2019-bbc-china-cables-camps",
    title: "Data leak reveals how China ‘brainwashes’ Uighurs in prison camps",
    url: "https://www.bbc.co.uk/news/world-asia-china-50511063",
    publisher: "BBC News",
    accessedAt: "2026-07-22",
    publicationYear: 2019,
    contentType: "reporting",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["xinjiang", "china-cables", "detention", "leaked-documents"],
    evidenceStatus: "unverified",
    hnStoryId: "21622138",
    hnSnapshot: snapshot(329, 148),
    notes:
      "Review the leaked documents, authentication method, expert analysis, and Chinese government response directly; retain quotation marks around translated policy terminology where needed.",
  },
  {
    id: "lead-2019-chanind-websites-in-china",
    title: "So you want your app/website to work in China",
    url: "https://chanind.github.io/china/2019/01/19/launching-an-app-or-website-in-china.html",
    publisher: "Chanind",
    accessedAt: "2026-07-22",
    publishedAt: "2019-01-19",
    contentType: "analysis",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["web-development", "hosting", "cdn", "great-firewall"],
    evidenceStatus: "unverified",
    hnStoryId: "19457709",
    hnSnapshot: snapshot(327, 157),
    notes:
      "Useful dated practitioner guide, not a universal compliance manual. Recheck ICP, hosting, CDN, DNS, performance, and regulatory claims against current primary guidance.",
  },
  {
    id: "lead-2025-akamai-china-cdn-shutdown",
    title: "Akamai to shut down its CDN operations in China",
    url: "https://content.akamai.com/index.php/email/emailWebview?email=NjQyLVNLTi00NDkAAAGWBQgHSPFMp0ow2aF67IAbDOB0c1pNppYjWH8ZCkGxrVi4pDs7pT_120NiLvARghhVOBbaIJqps_3Ii2OZlixo3IPjhpR79JsTe-0&trk=comments_comments-list_comment-text",
    publisher: "Akamai",
    accessedAt: "2026-07-22",
    publicationYear: 2025,
    contentType: "primary",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["akamai", "cdn", "china-operations", "infrastructure"],
    evidenceStatus: "unverified",
    hnStoryId: "42603585",
    hnSnapshot: snapshot(327, 143),
    notes:
      "Ephemeral email-view URL. Find a stable Akamai announcement or customer notice and establish product scope, dates, migration path, and whether partner delivery continues.",
  },
  {
    id: "lead-2017-techcrunch-pboc-ico-ban",
    title: "China's Central Bank Bans ICOs",
    url: "https://techcrunch.com/2017/09/04/chinas-central-bank-has-banned-icos/amp/",
    publisher: "TechCrunch",
    accessedAt: "2026-07-22",
    publishedAt: "2017-09-04",
    contentType: "reporting",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["icos", "cryptocurrency", "pboc", "financial-regulation"],
    evidenceStatus: "unverified",
    hnStoryId: "15166607",
    hnSnapshot: snapshot(326, 373),
    notes:
      "Secondary breaking-news account. Resolve the joint regulator notice, its legal scope, implementation, and the difference between ICO restrictions and later cryptocurrency measures.",
  },
  {
    id: "lead-2021-cbc-canada-uyghur-motion",
    title:
      "Canada's parliament votes to label China's persecution of Uighurs as genocide",
    url: "https://www.cbc.ca/news/politics/uighur-genocide-motion-vote-1.5922711",
    publisher: "CBC News",
    accessedAt: "2026-07-22",
    publicationYear: 2021,
    contentType: "reporting",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["canada", "uyghurs", "parliament", "genocide-motion"],
    evidenceStatus: "unverified",
    hnStoryId: "26253886",
    hnSnapshot: snapshot(326, 172),
    notes:
      "Record the exact nonbinding motion, vote, executive position, and legal effect; a parliamentary label is not a judicial finding.",
  },
  {
    id: "lead-2019-gizmodo-leica-censorship",
    title: "China Bans the Word ‘Leica’ on Social Media",
    url: "https://gizmodo.com/china-bans-the-word-leica-on-social-media-1834163199",
    publisher: "Gizmodo",
    accessedAt: "2026-07-22",
    publicationYear: 2019,
    contentType: "reporting",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["leica", "advertising", "social-media", "censorship"],
    evidenceStatus: "unverified",
    hnStoryId: "19712564",
    hnSnapshot: snapshot(324, 260),
    notes:
      "Headline-level ban claims require platform-by-platform tests, dates, archived results, the advertisement itself, and responses from Leica and platforms.",
  },
  {
    id: "lead-2020-hn-youtube-china-comments",
    title:
      "Ask HN: How long has Google been censoring YouTube comments critical of China?",
    url: "https://news.ycombinator.com/item?id=23221264",
    publisher: "Hacker News",
    accessedAt: "2026-07-22",
    publishedAt: "2020-05-18",
    contentType: "discussion",
    claimedGrade: "D",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["youtube", "comment-moderation", "china", "commentary"],
    evidenceStatus: "unverified",
    hnStoryId: "23221264",
    hnSnapshot: snapshot(324, 108),
    notes:
      "Unverified user test with inflammatory wording. Use only to formulate a moderation question; seek reproducible tests, contemporaneous platform statements, and later corrections. Do not reproduce the submitted slurs.",
  },
  {
    id: "lead-2021-nasdaq-bitcoin-hashrate-blackouts",
    title: "Bitcoin mining hash rate drops as blackouts instituted in China",
    url: "https://www.nasdaq.com/articles/bitcoin-mining-hash-rate-drops-as-blackouts-instituted-in-china-2021-04-16",
    publisher: "Nasdaq",
    accessedAt: "2026-07-22",
    publishedAt: "2021-04-16",
    contentType: "reporting",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["bitcoin", "mining", "hashrate", "power-outages"],
    evidenceStatus: "unverified",
    hnStoryId: "26849652",
    hnSnapshot: snapshot(322, 407),
    notes:
      "Hash-rate estimates and blackout timing support a correlation, not a complete causal allocation. Capture estimator, pool coverage, geography, and competing explanations.",
  },
  {
    id: "lead-2017-trustnodes-bitcoin-exit-ban",
    title:
      "China Bans Bitcoin Executives from Leaving Country, Miners ‘Preparing for Worst’",
    url: "http://www.trustnodes.com/2017/09/19/china-bans-bitcoin-executives-leaving-country-miners-preparing-worst?",
    publisher: "Trustnodes",
    accessedAt: "2026-07-22",
    publishedAt: "2017-09-19",
    contentType: "reporting",
    claimedGrade: "D",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["bitcoin", "exit-bans", "mining", "cryptocurrency"],
    evidenceStatus: "unverified",
    hnStoryId: "15290117",
    hnSnapshot: snapshot(322, 260),
    notes:
      "Low-confidence secondary claim with unnamed sourcing. Do not use without strong independent corroboration or a primary legal/official record.",
  },
  {
    id: "lead-2019-reuters-china-737-max-suspension",
    title:
      "China orders its airlines to suspend use of Boeing 737 Max aircraft",
    url: "https://www.reuters.com/article/us-ethiopia-airlines-china/china-orders-its-airlines-to-suspend-use-of-boeing-737-max-aircraft-media-idUSKBN1QS01Z",
    publisher: "Reuters",
    accessedAt: "2026-07-22",
    publishedAt: "2019-03-11",
    contentType: "reporting",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["boeing-737-max", "caac", "aviation-safety", "airlines"],
    evidenceStatus: "unverified",
    hnStoryId: "19356138",
    hnSnapshot: snapshot(322, 199),
    notes:
      "Breaking-news chronology should be paired with the CAAC directive, affected fleet and timing, accident record, and later international grounding decisions.",
  },
  {
    id: "lead-2018-shanghaiist-redcore-browser",
    title:
      "China’s first ‘fully homegrown’ web browser found to be Google Chrome clone",
    url: "https://shanghai.ist/2018/08/16/chinas-first-fully-homegrown-web-browser-found-to-be-google-chrome-clone/",
    publisher: "Shanghaiist",
    accessedAt: "2026-07-22",
    publishedAt: "2018-08-16",
    contentType: "reporting",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["redcore", "chromium", "browser", "technology-claims"],
    evidenceStatus: "unverified",
    hnStoryId: "17774608",
    hnSnapshot: snapshot(321, 171),
    notes:
      "Verify the company's exact ‘homegrown’ claim, software artifacts or teardown, Chromium licensing, investor materials, and response; clone is a conclusion requiring technical evidence.",
  },
  {
    id: "lead-2017-wapo-apple-world-internet-conference",
    title:
      "Apple CEO backs China’s ‘open’ Internet vision as censorship reaches new heights",
    url: "https://www.washingtonpost.com/news/worldviews/wp/2017/12/04/apple-ceo-backs-chinas-vision-of-an-open-internet-as-censorship-reaches-new-heights/",
    publisher: "The Washington Post",
    accessedAt: "2026-07-22",
    publishedAt: "2017-12-04",
    contentType: "reporting",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["apple", "tim-cook", "world-internet-conference", "censorship"],
    evidenceStatus: "unverified",
    paywall: true,
    hnStoryId: "15849184",
    hnSnapshot: snapshot(319, 310),
    notes:
      "Separate Cook's exact remarks from the article's framing and pair them with the conference transcript, contemporary App Store removals, and Apple's stated policy.",
  },
  {
    id: "lead-2017-npr-china-foreign-waste-ban",
    title: "Recycling Chaos in U.S. As China Bans ‘Foreign Waste’",
    url: "https://www.npr.org/2017/12/09/568797388/recycling-chaos-in-u-s-as-china-bans-foreign-waste",
    publisher: "NPR",
    accessedAt: "2026-07-22",
    publishedAt: "2017-12-09",
    contentType: "reporting",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["recycling", "national-sword", "waste-trade", "municipal-policy"],
    evidenceStatus: "unverified",
    hnStoryId: "15888827",
    hnSnapshot: snapshot(318, 233),
    notes:
      "Useful early impact report. Resolve covered waste categories and contamination thresholds, then distinguish immediate US disruption from later market and municipal adaptation.",
  },
  {
    id: "lead-2015-fortune-us-china-manufacturing-costs",
    title: "U.S. Manufacturing costs are almost as low as China’s",
    url: "http://fortune.com/2015/06/26/fracking-manufacturing-costs/",
    publisher: "Fortune",
    accessedAt: "2026-07-22",
    publishedAt: "2015-06-26",
    contentType: "analysis",
    sourceOrigin: "user-sourcebook",
    reviewState: "supplied",
    topics: ["manufacturing-costs", "energy", "reshoring", "competitiveness"],
    evidenceStatus: "unverified",
    hnStoryId: "9794694",
    hnSnapshot: snapshot(318, 160),
    notes:
      "A dated cost-comparison thesis. Capture the underlying model, industry and regional mix, energy and labor assumptions, exchange rates, and whether ‘almost’ survives later data.",
  },
];
