type StoryCluster =
  | "technology-ai"
  | "climate-energy"
  | "trade-industry"
  | "governance-rights"
  | "security-diplomacy"
  | "society-culture"
  | "economy-society"
  | "science-infrastructure";

type Seed = readonly [
  hnId: string,
  title: string,
  url: string,
  publisher: string,
  publicationYear: number,
  contentType: "research" | "reporting" | "analysis",
  cluster: StoryCluster,
  accessStatus: "reachable" | "paywalled" | "restricted" | "unstable",
  redirectResolved: boolean,
];

const clusterMetadata: Record<
  StoryCluster,
  { topics: string[]; limit: string }
> = {
  "technology-ai": {
    topics: [
      "china",
      "technology",
      "artificial-intelligence",
      "digital-policy",
    ],
    limit:
      "Verify the underlying technical artifact, policy text, company record, benchmark, and implementation state before reusing a capability or competition claim.",
  },
  "climate-energy": {
    topics: ["china", "climate", "energy", "environment"],
    limit:
      "Preserve the source period, unit, geography, baseline, and model or inventory method; an announced project or short trend does not establish a durable system outcome.",
  },
  "trade-industry": {
    topics: ["china", "trade", "industry", "supply-chains"],
    limit:
      "Separate proposals, company statements, reported negotiations, and effective legal measures, and verify values against compatible primary trade and industry records.",
  },
  "governance-rights": {
    topics: ["china", "governance", "law", "rights"],
    limit:
      "Locate the controlling record and distinguish an official position, reported allegation, legal finding, enforcement event, and observed outcome.",
  },
  "security-diplomacy": {
    topics: ["china", "security", "diplomacy", "geopolitics"],
    limit:
      "Preserve attribution, jurisdiction, chronology, and uncertainty; a reported concern or stated intent does not prove operational control or a completed policy change.",
  },
  "society-culture": {
    topics: ["china", "society", "culture", "daily-life"],
    limit:
      "Treat individual accounts and striking examples as bounded narratives until population, regional, historical, and policy context has been reviewed.",
  },
  "economy-society": {
    topics: ["china", "economy", "labor", "living-conditions"],
    limit:
      "Keep nominal and real values, stocks and flows, national and local measures, and reported experience on compatible periods and populations.",
  },
  "science-infrastructure": {
    topics: ["china", "science", "infrastructure", "research"],
    limit:
      "Confirm the original research or mission record, technical definition, schedule, funding basis, and observed result before describing scale or success.",
  },
};

const seeds = [
  [
    "46630369",
    "Photos capture the breathtaking scale of China's wind and solar buildout",
    "https://e360.yale.edu/digest/china-renewable-photo-essay",
    "Yale Environment 360",
    2026,
    "reporting",
    "climate-energy",
    "reachable",
    false,
  ],
  [
    "45732800",
    "China has added forest the size of Texas since 1990",
    "https://e360.yale.edu/digest/china-new-forest-report",
    "Yale Environment 360",
    2025,
    "reporting",
    "climate-energy",
    "reachable",
    false,
  ],
  [
    "45267643",
    "U.S. investors, Trump close in on TikTok deal with China",
    "https://www.wsj.com/tech/details-emerge-on-u-s-china-tiktok-deal-594e009f",
    "The Wall Street Journal",
    2025,
    "reporting",
    "trade-industry",
    "paywalled",
    false,
  ],
  [
    "47920315",
    "China blocks Meta's acquisition of AI startup Manus",
    "https://www.cnbc.com/2026/04/27/meta-manus-china-blocks-acquisition-ai-startup.html",
    "CNBC",
    2026,
    "reporting",
    "technology-ai",
    "restricted",
    false,
  ],
  [
    "49425819",
    "One corner of China’s internet is insisting that the Tang Dynasty never existed",
    "https://www.cnn.com/2026/08/19/style/china-tang-dynasty-never-existed-hoax-intl-hnk",
    "CNN",
    2026,
    "reporting",
    "society-culture",
    "reachable",
    false,
  ],
  [
    "46575902",
    "China applies to put 200K satellites in space after calling Starlink crash risk",
    "https://www.scmp.com/news/china/science/article/3339493/china-applies-put-200000-satellites-space-after-calling-starlink-crash-risk",
    "South China Morning Post",
    2026,
    "reporting",
    "science-infrastructure",
    "reachable",
    false,
  ],
  [
    "46075305",
    "China's BEV trucks and the end of diesel's dominance",
    "https://cleantechnica.com/2025/11/26/chinas-bev-trucks-and-the-end-of-diesels-dominance/",
    "CleanTechnica",
    2025,
    "analysis",
    "trade-industry",
    "reachable",
    false,
  ],
  [
    "49415187",
    "Nearly 3M Teslas recalled in China over hidden door handles",
    "https://www.bbc.com/news/articles/c4g6ggdg030o",
    "BBC News",
    2026,
    "reporting",
    "trade-industry",
    "reachable",
    false,
  ],
  [
    "45313127",
    "China's 200M gig workers are a warning for the world",
    "https://www.economist.com/leaders/2025/09/18/chinas-200m-gig-workers-are-a-warning-for-the-world",
    "The Economist",
    2025,
    "analysis",
    "economy-society",
    "paywalled",
    false,
  ],
  [
    "49110319",
    "China begins producing advanced chipmaking deep-ultraviolet lithography machines",
    "https://www.reuters.com/world/china/china-starts-production-home-grown-immersion-duv-chipmaking-tools-source-2026-07-28/",
    "Reuters",
    2026,
    "reporting",
    "technology-ai",
    "restricted",
    false,
  ],
  [
    "49479898",
    "Barrier lake continues to pose flood risk, China warns",
    "https://kathmandupost.com/national/2026/08/28/barrier-lake-continues-to-pose-flood-risk-china-warns",
    "The Kathmandu Post",
    2026,
    "reporting",
    "climate-energy",
    "reachable",
    false,
  ],
  [
    "45681269",
    "Why China is winning the trade war",
    "https://www.economist.com/leaders/2025/10/23/why-china-is-winning-the-trade-war",
    "The Economist",
    2025,
    "analysis",
    "trade-industry",
    "paywalled",
    false,
  ],
  [
    "46060935",
    "China Has Three Reusable Rockets Ready for Their Debut Flights",
    "https://www.china-in-space.com/p/china-has-three-reusable-rockets",
    "China in Space",
    2025,
    "reporting",
    "science-infrastructure",
    "reachable",
    false,
  ],
  [
    "45597236",
    "China Has Overtaken America",
    "https://paulkrugman.substack.com/p/china-has-overtaken-america",
    "Paul Krugman",
    2025,
    "analysis",
    "economy-society",
    "reachable",
    false,
  ],
  [
    "49155940",
    "The Future, Made in China",
    "https://www.newyorker.com/magazine/2026/08/10/the-future-made-in-china",
    "The New Yorker",
    2026,
    "analysis",
    "society-culture",
    "reachable",
    false,
  ],
  [
    "48855895",
    "China's public QR codes are being hijacked to redirect users to porn and scams",
    "https://www.sixthtone.com/news/1018752",
    "Sixth Tone",
    2026,
    "reporting",
    "society-culture",
    "reachable",
    true,
  ],
  [
    "49698664",
    'China\'s Regulators Take Aim at "AI Boyfriends"',
    "https://spectrum.ieee.org/china-ai-chatbot-regulation",
    "IEEE Spectrum",
    2026,
    "reporting",
    "technology-ai",
    "reachable",
    false,
  ],
  [
    "49110166",
    "Boarding China's Last Bus",
    "https://asteriskmag.com/issues/15/chinas-last-bus",
    "Asterisk Magazine",
    2026,
    "reporting",
    "society-culture",
    "reachable",
    false,
  ],
  [
    "49548530",
    "A dark horse enters China's AI race: StartLux",
    "https://chinaonchina.com/article/chen-dawei-returns-enters-the-large-model-sector",
    "China on China",
    2026,
    "reporting",
    "technology-ai",
    "unstable",
    false,
  ],
  [
    "45719820",
    "Canada Set to Side with China on EVs",
    "https://www.thewirechina.com/2025/10/26/canada-set-to-side-with-china-on-evs/",
    "The Wire China",
    2025,
    "reporting",
    "trade-industry",
    "reachable",
    false,
  ],
  [
    "48705276",
    "Can China build its own ASML?",
    "https://nikkei.shorthandstories.com/can-china-build-its-own-asml/",
    "Nikkei Asia",
    2026,
    "analysis",
    "technology-ai",
    "restricted",
    false,
  ],
  [
    "46460867",
    "China's BYD set to overtake Tesla as top EV seller",
    "https://www.bbc.com/news/articles/cj9rjwpvmpzo",
    "BBC News",
    2026,
    "reporting",
    "trade-industry",
    "reachable",
    false,
  ],
  [
    "49146696",
    "How China Keeps Tabs on Foreigners",
    "https://www.nytimes.com/2026/08/02/world/asia/china-surveillance-foreigners-database.html",
    "The New York Times",
    2026,
    "reporting",
    "governance-rights",
    "paywalled",
    false,
  ],
  [
    "46307819",
    "How China built its Manhattan Project rival west AI chips",
    "https://www.reuters.com/world/china/how-china-built-its-manhattan-project-rival-west-ai-chips-2025-12-17/",
    "Reuters",
    2025,
    "reporting",
    "technology-ai",
    "restricted",
    false,
  ],
  [
    "46417651",
    "China launches live-fire drills encircling Taiwan",
    "https://www.theguardian.com/world/2025/dec/29/china-live-fire-military-drills-around-taiwan",
    "The Guardian",
    2025,
    "reporting",
    "security-diplomacy",
    "reachable",
    false,
  ],
  [
    "47083036",
    "China confirms visa-free travel for UK and Canadian nationals",
    "https://www.bbc.com/news/articles/c875d3d3x34o",
    "BBC News",
    2026,
    "reporting",
    "society-culture",
    "reachable",
    false,
  ],
  [
    "48856412",
    "China may restrict foreign access to Chinese open-source AI models",
    "https://www.reuters.com/technology/artificial-intelligence/china-weighs-silicon-curtain-around-sought-after-ai-models-2026-07-08/",
    "Reuters",
    2026,
    "reporting",
    "technology-ai",
    "restricted",
    false,
  ],
  [
    "49573370",
    "New Zealand is determined not to keep China's espionage a secret",
    "https://www.lowyinstitute.org/the-interpreter/new-zealand-is-determined-not-to-keep-china-s-espionage-a-secret",
    "Lowy Institute",
    2026,
    "analysis",
    "security-diplomacy",
    "reachable",
    false,
  ],
  [
    "45305922",
    "China's BYD is sued over 'slave-like' labor conditions",
    "https://qz.com/brazil-sues-byd-over-slave-like-labor-conditions-1851782704",
    "Quartz",
    2025,
    "reporting",
    "trade-industry",
    "restricted",
    false,
  ],
  [
    "46444908",
    "Xi Jinping Vows to Reunify China and Taiwan in New Year's Eve Speech",
    "https://www.theguardian.com/world/2025/dec/31/xi-jinping-vows-reunification-china-taiwan-new-years-eve-speech",
    "The Guardian",
    2025,
    "reporting",
    "security-diplomacy",
    "reachable",
    false,
  ],
  [
    "49367924",
    "How China Saved the Global Oil Market",
    "https://www.commoditycontext.com/p/public-how-china-saved-the-global-oil-market",
    "Commodity Context",
    2026,
    "analysis",
    "climate-energy",
    "reachable",
    false,
  ],
  [
    "48865717",
    "China's Open AI Models Are Advancing Its Global Soft Power",
    "https://www.noemamag.com/chinas-open-ai-models-are-advancing-its-global-soft-power/",
    "Noema Magazine",
    2026,
    "analysis",
    "technology-ai",
    "reachable",
    false,
  ],
  [
    "45881241",
    "Apple Pulls China's Top Gay Dating Apps After Government Order",
    "https://www.wired.com/story/apple-removes-gay-dating-apps-china-app-store/",
    "Wired",
    2025,
    "reporting",
    "governance-rights",
    "reachable",
    false,
  ],
  [
    "46965345",
    "China's Data Center Boom: A View from Zhangjiakou (2025)",
    "https://sinocities.org/p/chinas-data-center-boom-a-view-from",
    "Sinocities",
    2026,
    "reporting",
    "technology-ai",
    "reachable",
    true,
  ],
  [
    "45379795",
    "China Bought $12.6B in U.S. Soybeans Last Year. Now, It's $0",
    "https://www.nytimes.com/2025/09/25/business/china-soybean-sales-farmers.html",
    "The New York Times",
    2025,
    "reporting",
    "trade-industry",
    "paywalled",
    false,
  ],
  [
    "45262435",
    "Why one of the most brilliant AI scientists left the US for China",
    "https://www.theguardian.com/news/ng-interactive/2025/sep/16/song-chun-zhu-why-one-of-the-worlds-most-brilliant-ai-scientists-left-the-us-for-china",
    "The Guardian",
    2025,
    "reporting",
    "technology-ai",
    "reachable",
    false,
  ],
  [
    "48151863",
    "Travelers on Air Force One ordered to throw away gifts, phones after China trip",
    "https://techcrunch.com/2026/05/15/us-orders-travelers-on-air-force-one-to-throw-away-gifts-pins-and-burner-phones-after-china-trip/",
    "TechCrunch",
    2026,
    "reporting",
    "security-diplomacy",
    "reachable",
    false,
  ],
  [
    "45565164",
    "Netherlands cracks down on China-owned chip firm over security risk",
    "https://www.bbc.com/news/articles/ckgk21nng0vo",
    "BBC News",
    2025,
    "reporting",
    "trade-industry",
    "reachable",
    false,
  ],
  [
    "48207335",
    "Mass surveillance of foreigners in China revealed by abandoned demo dashboard",
    "https://netaskari.substack.com/p/sharp-eyes-how-to-track-a-foreigner",
    "NetAskari",
    2026,
    "reporting",
    "security-diplomacy",
    "reachable",
    false,
  ],
  [
    "49311888",
    "US to tell partners they must pick sides in AI race with China",
    "https://www.reuters.com/world/china/us-tell-partners-they-must-pick-sides-ai-race-with-china-2026-08-14/",
    "Reuters",
    2026,
    "reporting",
    "security-diplomacy",
    "restricted",
    false,
  ],
  [
    "46616843",
    "China announces record $1.2T trade surplus despite Trump tariffs",
    "https://www.bbc.com/news/articles/c9wx1v84rzyo",
    "BBC News",
    2026,
    "reporting",
    "trade-industry",
    "reachable",
    false,
  ],
  [
    "47450014",
    "China could be the biggest public funder of science within two years",
    "https://www.nature.com/articles/d41586-026-00618-5",
    "Nature",
    2026,
    "reporting",
    "science-infrastructure",
    "reachable",
    false,
  ],
  [
    "46280806",
    "Meta tolerates rampant ad fraud from China to safeguard billions in revenue",
    "https://www.reuters.com/investigations/meta-tolerates-rampant-ad-fraud-china-safeguard-billions-revenue-2025-12-15/",
    "Reuters",
    2025,
    "reporting",
    "governance-rights",
    "restricted",
    false,
  ],
  [
    "48871116",
    "China recovered its first reusable rocket and showed a new way to do it",
    "https://arstechnica.com/space/2026/07/china-recovered-its-first-reusable-rocket-and-showed-a-new-way-to-do-it/",
    "Ars Technica",
    2026,
    "reporting",
    "science-infrastructure",
    "restricted",
    false,
  ],
  [
    "47213754",
    "Photos show China's low-cost lifestyle in semiabandoned housing complexes",
    "https://apnews.com/photo-gallery/china-property-cheap-housing-abandoned-9f642584aea206204dcfdd10afb25861",
    "Associated Press",
    2026,
    "reporting",
    "economy-society",
    "restricted",
    false,
  ],
  [
    "46404094",
    "A Tale of Two Leaks: How Hackers Breached the Great Firewall of China [video]",
    "https://media.ccc.de/v/39c3-a-tale-of-two-leaks-how-hackers-breached-the-great",
    "Chaos Computer Club",
    2025,
    "reporting",
    "technology-ai",
    "reachable",
    false,
  ],
  [
    "48155729",
    "Is China using fentanyl as a weapon against the United States?",
    "https://en.unav.edu/web/global-affairs/esta-china-usando-el-fentanilo-como-arma-contra-estados-unidos",
    "University of Navarra",
    2026,
    "analysis",
    "security-diplomacy",
    "reachable",
    false,
  ],
  [
    "48110441",
    "California Mayor Resigns, Admitting to Being an Agent for China",
    "https://time.com/article/2026/05/12/arcadia-california-mayor-eileen-wang-agent-china/",
    "Time",
    2026,
    "reporting",
    "security-diplomacy",
    "restricted",
    false,
  ],
  [
    "48630678",
    "China is having another AI moment",
    "https://www.economist.com/china/2026/06/21/china-is-having-another-ai-moment",
    "The Economist",
    2026,
    "analysis",
    "technology-ai",
    "paywalled",
    false,
  ],
  [
    "46966522",
    "I Just Returned from China. We Are Not Winning",
    "https://www.nytimes.com/2026/02/10/opinion/china-ai-ev-trump.html",
    "The New York Times",
    2026,
    "analysis",
    "economy-society",
    "paywalled",
    false,
  ],
  [
    "48101209",
    "Elon Musk and Tim Cook among CEOs expected to accompany Trump on China trip",
    "https://www.bbc.com/news/articles/c5yx757w048o",
    "BBC News",
    2026,
    "reporting",
    "security-diplomacy",
    "reachable",
    false,
  ],
  [
    "45324846",
    "China to launch new K Visa to attract foreign STEM talent",
    "https://kpmg.com/xx/en/our-insights/gms-flash-alert/flash-alert-2025-161.html",
    "KPMG",
    2025,
    "analysis",
    "society-culture",
    "reachable",
    false,
  ],
  [
    "47521955",
    "She uncovered a terrifying lab hidden in California, with alleged ties to China",
    "https://www.latimes.com/california/story/2026-03-25/she-uncovered-terrifying-lab-hidden-in-california-with-alleged-ties-to-china",
    "Los Angeles Times",
    2026,
    "reporting",
    "security-diplomacy",
    "reachable",
    false,
  ],
  [
    "47121498",
    "Coal power drops in China and India for first time in 52 years",
    "https://www.carbonbrief.org/analysis-coal-power-drops-in-china-and-india-for-first-time-in-52-years-after-clean-energy-records/",
    "Carbon Brief",
    2026,
    "analysis",
    "climate-energy",
    "reachable",
    false,
  ],
  [
    "46443841",
    "China mandates 50% domestic equipment rule for chipmakers",
    "https://www.reuters.com/world/china/china-mandates-50-domestic-equipment-rule-chipmakers-sources-say-2025-12-30/",
    "Reuters",
    2025,
    "reporting",
    "technology-ai",
    "restricted",
    false,
  ],
  [
    "47940086",
    "Why China's Affordable AI Is a Worry for Silicon Valley",
    "https://www.bloomberg.com/news/articles/2026-04-27/why-china-s-deepseek-qwen-and-moonshot-are-a-worry-for-us-ai-rivals",
    "Bloomberg",
    2026,
    "analysis",
    "technology-ai",
    "paywalled",
    false,
  ],
  [
    "45652799",
    "China imports no US soybeans in September for first time in seven years",
    "https://www.reuters.com/world/china/china-imports-no-us-soybeans-september-first-time-seven-years-2025-10-20/",
    "Reuters",
    2025,
    "reporting",
    "trade-industry",
    "restricted",
    false,
  ],
  [
    "47874732",
    "UK Biobank health data listed for sale in China, government confirms",
    "https://www.bbc.co.uk/news/articles/cpvxgl3n138o",
    "BBC News",
    2026,
    "reporting",
    "security-diplomacy",
    "reachable",
    false,
  ],
  [
    "46198093",
    "Trump greenlights Nvidia H200 AI chip sales to China",
    "https://www.cnbc.com/2025/12/08/trump-nvidia-h200-sales-china.html",
    "CNBC",
    2025,
    "reporting",
    "technology-ai",
    "restricted",
    false,
  ],
  [
    "45543888",
    "Trump hits China with an additional 100% tariff and software export controls",
    "https://www.wsj.com/politics/policy/trump-china-tariffs-rare-earths-xi-meeting-8053c81a",
    "The Wall Street Journal",
    2025,
    "reporting",
    "trade-industry",
    "paywalled",
    false,
  ],
  [
    "46843333",
    "China's 'gold fever' sparks US$1B scandal as trading platform collapses",
    "https://www.scmp.com/economy/china-economy/article/3341633/chinas-gold-fever-sparks-us1-billion-scandal-trading-platform-collapses",
    "South China Morning Post",
    2026,
    "reporting",
    "economy-society",
    "reachable",
    false,
  ],
  [
    "45994449",
    "China's shadow Navy trains to take Taiwan",
    "https://www.reuters.com/graphics/USA-CHINA/TAIWAN-INVASION/zjpqdekmlvx/",
    "Reuters",
    2025,
    "reporting",
    "security-diplomacy",
    "reachable",
    false,
  ],
  [
    "46609733",
    'China obsesses over America\'s "kill line"',
    "https://www.economist.com/china/2026/01/12/china-obsesses-over-americas-kill-line",
    "The Economist",
    2026,
    "analysis",
    "economy-society",
    "paywalled",
    false,
  ],
  [
    "48943519",
    "Xi pitches China as leader of a new global AI order",
    "https://www.reuters.com/world/asia-pacific/chinas-xi-promotes-chinas-commitment-ai-access-speech-shanghai-conference-2026-07-17/",
    "Reuters",
    2026,
    "reporting",
    "security-diplomacy",
    "restricted",
    false,
  ],
  [
    "48857348",
    "China lands a reusable rocket for the first time, state media says",
    "https://www.bbc.com/news/articles/cm2rmmx86pdo",
    "BBC News",
    2026,
    "reporting",
    "science-infrastructure",
    "reachable",
    false,
  ],
  [
    "45275070",
    "China bans technology companies from buying Nvidia AI chips",
    "https://www.ft.com/content/09c93e6b-a6bb-4c20-b079-e489d8d4bd90",
    "Financial Times",
    2025,
    "reporting",
    "technology-ai",
    "paywalled",
    false,
  ],
  [
    "46885414",
    "China to ban hidden door handles on cars starting in 2027",
    "https://apnews.com/article/china-car-door-handles-ev-tesla-0c8a310e8d5b38804a725ec698c84f8f",
    "Associated Press",
    2026,
    "reporting",
    "trade-industry",
    "restricted",
    false,
  ],
  [
    "45875878",
    "As the U.S. and E.U. retreat on climate, China takes a leadership role",
    "https://e360.yale.edu/features/china-climate-diplomacy",
    "Yale Environment 360",
    2025,
    "analysis",
    "climate-energy",
    "reachable",
    false,
  ],
  [
    "45699324",
    "China releases the UBIOS standard as a Huawei-backed UEFI alternative",
    "https://www.tomshardware.com/software/china-releases-ubios-standard-to-replace-uefi-huawei-backed-bios-firmware-replacement-charges-chinas-domestic-computing-goals",
    "Tom's Hardware",
    2025,
    "reporting",
    "technology-ai",
    "reachable",
    false,
  ],
  [
    "47257274",
    "China tells top refiners to suspend diesel and gasoline exports",
    "https://www.bloomberg.com/news/articles/2026-03-05/china-tells-top-refiners-to-suspend-diesel-and-gasoline-exports",
    "Bloomberg",
    2026,
    "reporting",
    "climate-energy",
    "paywalled",
    false,
  ],
  [
    "47657652",
    "China fell for a lobster: What an AI assistant tells us about Beijing's ambition",
    "https://www.bbc.com/news/articles/cy41n17e23go",
    "BBC News",
    2026,
    "reporting",
    "society-culture",
    "reachable",
    false,
  ],
  [
    "47111731",
    "Poland bans camera-equipped Chinese cars from military bases",
    "https://www.theregister.com/security/2026/02/19/poland-bans-chinese-cars-from-military-bases/4879278",
    "The Register",
    2026,
    "reporting",
    "security-diplomacy",
    "reachable",
    true,
  ],
  [
    "45872233",
    "China bans foreign AI chips from state-funded data centers",
    "https://www.reuters.com/world/china/china-bans-foreign-ai-chips-state-funded-data-centres-sources-say-2025-11-05/",
    "Reuters",
    2025,
    "reporting",
    "technology-ai",
    "restricted",
    false,
  ],
  [
    "49605046",
    "Canada holds first defense talks with China in more than eight years",
    "https://www.scmp.com/news/china/diplomacy/article/3366477/canada-and-china-thaw-continues-militaries-hold-first-talks-8-years-amid-us-pressure",
    "South China Morning Post",
    2026,
    "reporting",
    "security-diplomacy",
    "reachable",
    false,
  ],
  [
    "48943166",
    "People in many countries now view China more positively than the U.S.",
    "https://www.pewresearch.org/global/2026/07/15/people-in-many-countries-now-view-china-more-positively-than-the-u-s/",
    "Pew Research Center",
    2026,
    "research",
    "security-diplomacy",
    "reachable",
    false,
  ],
  [
    "48096860",
    "Why China believes America will flame out",
    "https://www.theatlantic.com/international/2026/05/china-trump-american-decline/687087/",
    "The Atlantic",
    2026,
    "analysis",
    "security-diplomacy",
    "reachable",
    false,
  ],
  [
    "46986338",
    "China's CO2 emissions have been flat or falling for 21 months",
    "https://www.carbonbrief.org/analysis-chinas-co2-emissions-have-now-been-flat-or-falling-for-21-months/",
    "Carbon Brief",
    2026,
    "analysis",
    "climate-energy",
    "reachable",
    false,
  ],
  [
    "46461182",
    "China taxes condoms and contraceptive drugs in bid to spur birth rate",
    "https://www.reuters.com/business/healthcare-pharmaceuticals/china-taxes-condoms-contraceptive-drugs-bid-spur-birth-rate-2026-01-02/",
    "Reuters",
    2026,
    "reporting",
    "society-culture",
    "restricted",
    false,
  ],
] as const satisfies readonly Seed[];

/**
 * Past-year China discovery intake from HN Algolia pages 0 through 6, frozen
 * on September 15, 2026. HN ranking is discovery context, not evidence.
 */
export const chinaHnPastYear20260915 = seeds.map(
  ([
    hnId,
    title,
    url,
    publisher,
    publicationYear,
    contentType,
    cluster,
    accessStatus,
    redirectResolved,
  ]) => ({
    id: `lead-hn-${publicationYear}-${hnId}`,
    title,
    url,
    publisher,
    publicationYear,
    contentType,
    topics: [...clusterMetadata[cluster].topics, `story-cluster:${cluster}`],
    notes: `Discovered through HN Algolia story ${hnId}. ${clusterMetadata[cluster].limit} HN popularity and discussion volume are discovery signals, not evidence of accuracy, importance, or editorial endorsement.`,
    accessedAt: "2026-09-15",
    sourceOrigin: "web-research" as const,
    collectionId: "china-hn-past-year-2026-09-15",
    reviewState: "metadata-checked" as const,
    disposition: "withheld" as const,
    accessStatus,
    urlStatus: redirectResolved
      ? ("redirect-resolved" as const)
      : ("supplied" as const),
    ...(redirectResolved ? { canonicalCheckedAt: "2026-09-15" } : {}),
    language: "English",
    translationStatus: "original-english" as const,
    evidenceStatus: "unverified" as const,
    paywall: accessStatus === "paywalled",
    decisionReason:
      accessStatus === "unstable"
        ? "Retained as a potentially distinctive thematic lead, but the publisher endpoint failed the September 15 transport check. Withheld pending a stable original-publisher read, corroboration, and editorial approval."
        : accessStatus === "restricted" || accessStatus === "paywalled"
          ? "Retained after publisher and metadata screening, but lawful full-text review was restricted during intake. Withheld pending source read, primary records, corroboration, and editorial approval."
          : "Retained after publisher, metadata, thematic-fit, and endpoint screening. Withheld pending a complete source read, primary records where available, claim-level corroboration, and editorial approval.",
  })
);
