const reviewed = <T extends object>(item: T) => ({
  accessedAt: "2026-07-22",
  sourceOrigin: "prior-intake",
  reviewState: "evidence-reviewed",
  evidenceStatus: "confirmed",
  reviewedAt: "2026-07-22",
  ...item,
});

/** Canonical lead records added to complete the one-Dispatch-to-one-lead migration. */
export const existingDispatchCanonicalSources = [
  reviewed({
    id: "lead-2026-simon-willison-kimi-k3",
    title: "Kimi K3",
    url: "https://simonwillison.net/2026/Jul/16/kimi-k3/",
    publisher: "Simon Willison’s Weblog",
    publishedAt: "2026-07-16",
    contentType: "analysis",
    topics: ["kimi-k3", "evaluation", "inference"],
    notes: "Reviewed hands-on test with explicitly bounded methodology.",
  }),
  reviewed({
    id: "lead-2026-epoch-us-china-eci",
    title: "US vs. China: Which Country Leads in AI?",
    url: "https://epoch.ai/data-insights/us-vs-china-eci",
    publisher: "Epoch AI",
    publishedAt: "2026-01-02",
    contentType: "research",
    topics: ["ai-capability", "methodology", "bilateral"],
    notes:
      "Reviewed historical capability-index methodology and dated estimate.",
  }),
  reviewed({
    id: "lead-2026-scio-world-ai-keynote-mobile",
    title: "Xi Jinping’s keynote address at the World AI Conference",
    url: "https://english.scio.gov.cn/m/topnews/2026-07/18/content_118605932.html",
    publisher: "State Council Information Office of the PRC",
    publishedAt: "2026-07-17",
    contentType: "primary",
    topics: ["ai-policy", "speech", "international-cooperation"],
    notes: "Reviewed official English publication of the policy address.",
  }),
  reviewed({
    id: "lead-2026-interconnects-kimi-k3",
    title: "Kimi K3 and the open-weights escalation",
    url: "https://www.interconnects.ai/p/kimi-k3-the-open-weights-escalation",
    publisher: "Interconnects",
    publishedAt: "2026-07-18",
    contentType: "analysis",
    topics: ["kimi-k3", "open-weights", "competition"],
    evidenceStatus: "disputed",
    notes:
      "Reviewed analysis; causal and strategic conclusions remain attributed.",
  }),
  reviewed({
    id: "lead-2012-chinafile-web-searches",
    title: "The Most Popular Chinese Web Searches of 2012",
    url: "https://www.chinafile.com/reporting-opinion/media/most-popular-chinese-web-searches-of-2012",
    publisher: "ChinaFile",
    publishedAt: "2012-12-21",
    contentType: "reporting",
    topics: ["search", "internet-culture", "2012"],
    notes:
      "Reviewed historical backfile source with period-specific ranking limits.",
  }),
  reviewed({
    id: "lead-2017-sixth-tone-amateur-programmers",
    title: "Amateur Programmers and Gaokao Games",
    url: "https://www.sixthtone.com/news/1000350",
    publisher: "Sixth Tone",
    publicationYear: 2017,
    contentType: "reporting",
    topics: ["programming", "education", "youth"],
    notes: "Reviewed culture and education reporting.",
  }),
  reviewed({
    id: "lead-2017-sixth-tone-student-council",
    title: "Power Play: Inside a Chinese Student Council",
    url: "https://www.sixthtone.com/news/1001240/power-play%3A-inside-a-chinese-student-council",
    publisher: "Sixth Tone",
    publicationYear: 2017,
    contentType: "reporting",
    topics: ["student-life", "universities", "culture"],
    notes: "Reviewed bounded account of student governance.",
  }),
  reviewed({
    id: "lead-2019-sixth-tone-basketball-fans",
    title: "Chinese Basketball Fans and Everyday Fandom",
    url: "https://www.sixthtone.com/news/1003932",
    publisher: "Sixth Tone",
    publicationYear: 2019,
    contentType: "reporting",
    topics: ["basketball", "fans", "everyday-life"],
    notes: "Reviewed culture reporting with a bounded participant sample.",
  }),
  reviewed({
    id: "lead-2021-rest-of-world-alpacas-douyin",
    title: "Alpacas and rural creators on Douyin",
    url: "https://restofworld.org/2021/alpacas-tiktok-china-douyin/",
    publisher: "Rest of World",
    publicationYear: 2021,
    contentType: "reporting",
    topics: ["douyin", "rural-creators", "platform-work"],
    notes: "Reviewed field reporting; platform-scale claims remain bounded.",
  }),
];
