import { AtlasReleaseSchema, type AtlasRelease } from "./schema";

const release = {
  slug: "semiconductor-control-chain",
  dossierSlug: "semiconductor-export-controls",
  version: "2026.07.21-2",
  title: "The semiconductor control chain",
  summary:
    "A source-led atlas of how the December 2024 US semiconductor controls moved from announcement to legal text, named companies, trade signals, and corporate disclosure.",
  methodology:
    "This release connects official records by date and documented relationship. Map lines show regulatory reach or disclosed supply-chain exposure, never inferred shipments. Trade movement is contextual correlation and does not establish policy causation.",
  publishedAt: "2026-07-21",
  retrievedAt: "2026-07-21",
  evidenceThrough: "2026-03-02",
  seriesThrough: "2025-12-31",
  editorialStatus: "published",
  provenance: "prototype",
  reviewState: "source-snapshot",
  relatedDispatchIds: [],
  sources: [
    {
      id: "source-bis-announcement",
      label: "Commerce strengthens semiconductor export controls",
      publisher: "Bureau of Industry and Security",
      sourceClass: "policy",
      evidenceRole: "supporting",
      canonicalUrl:
        "https://www.bis.gov/press-release/commerce-strengthens-export-controls-restrict-chinas-capability-produce-advanced-semiconductors-military",
      publishedAt: "2024-12-02",
      retrievedAt: "2026-07-21",
      datasetVintage: "December 2, 2024 announcement",
      language: "en",
      translationStatus: "original-english",
      recordId: "bis-2024-12-02-controls",
      notes:
        "Announcement-level source for 24 equipment types, three software-tool types, 140 Entity List additions, and 14 modifications. The Federal Register controls legal interpretation.",
    },
    {
      id: "source-federal-register-sme-rule",
      label: "89 FR 96790 · semiconductor manufacturing equipment controls",
      publisher: "Office of the Federal Register",
      sourceClass: "legal-record",
      evidenceRole: "controlling",
      canonicalUrl:
        "https://www.govinfo.gov/content/pkg/FR-2024-12-05/pdf/2024-28270.pdf",
      publishedAt: "2024-12-05",
      retrievedAt: "2026-07-21",
      datasetVintage: "89 FR 96790 · RIN 0694-AJ74",
      language: "en",
      translationStatus: "original-english",
      recordId: "fr-2024-28270",
      notes:
        "Controlling interim rule for advanced-computing, semiconductor-manufacturing-equipment, HBM, FN5, and FDP changes. December 31 applies only to the amendatory instructions named in the rule.",
    },
    {
      id: "source-federal-register-entity-rule",
      label: "89 FR 96830 · Entity List additions and modifications",
      publisher: "Office of the Federal Register",
      sourceClass: "legal-record",
      evidenceRole: "controlling",
      canonicalUrl:
        "https://www.govinfo.gov/content/pkg/FR-2024-12-05/pdf/2024-28267.pdf",
      publishedAt: "2024-12-05",
      retrievedAt: "2026-07-21",
      datasetVintage: "89 FR 96830 · RIN 0694-AJ77",
      language: "en",
      translationStatus: "original-english",
      recordId: "fr-2024-28267",
      notes:
        "Controlling final rule for 140 Entity List additions and 14 modifications, including ACM Research Shanghai and ACM Research Korea. Effective December 2; December 31 applies to requirements linked to FN5 designations.",
    },
    {
      id: "source-mofcom-response",
      label: "MOFCOM response to the December 2 semiconductor controls",
      publisher: "Ministry of Commerce of the People's Republic of China",
      sourceClass: "policy",
      evidenceRole: "supporting",
      canonicalUrl:
        "https://www.mofcom.gov.cn/xwfb/xwfyrth/art/2024/art_be61cee67b6340e59038896021e67453.html",
      publishedAt: "2024-12-02",
      retrievedAt: "2026-07-21",
      datasetVintage: "December 2, 2024 spokesperson response",
      language: "zh",
      translationStatus: "original-chinese",
      recordId: "mofcom-2024-12-02-semiconductor-response",
      notes:
        "Official PRC response. Its count of 136 Chinese entities is consistent with the US rule's 140 additions across China, Japan, Singapore, and South Korea; it is a government position, not independent impact evidence.",
    },
    {
      id: "source-trade-csl",
      label: "Consolidated Screening List",
      publisher: "International Trade Administration",
      sourceClass: "screening-data",
      evidenceRole: "enrichment",
      canonicalUrl: "https://www.trade.gov/consolidated-screening-list",
      retrievedAt: "2026-07-21",
      datasetVintage: "Retrieved July 21, 2026",
      revisionPolicy: "Automatically refreshed daily by Trade.gov.",
      language: "en",
      translationStatus: "original-english",
      recordId: "csl-enrichment-2026-07-21",
      notes:
        "Used only for alias and screening context. Trade.gov instructs readers to consult the underlying Federal Register publication for the official restriction.",
    },
    {
      id: "source-census-hs-contract",
      label: "Monthly US exports by Harmonized System code",
      publisher: "US Census Bureau",
      sourceClass: "methodology",
      evidenceRole: "methodology",
      canonicalUrl:
        "https://api.census.gov/data/timeseries/intltrade/exports/hs/variables.html",
      publishedAt: "2026-05-20",
      retrievedAt: "2026-07-21",
      datasetVintage: "API documentation revised May 20, 2026",
      revisionPolicy:
        "Updated monthly; previously released trade data are revised annually with the April statistics.",
      language: "en",
      translationStatus: "original-english",
      recordId: "census-hs8486-contract-2026-07-21",
      notes:
        "Defines ALL_VAL_MO and the preferred US-side extraction contract. It is methodology, not the value source for this release, because all Census trade API queries required a personal key at retrieval.",
    },
    {
      id: "source-un-comtrade-hs",
      label: "UN Comtrade preview · US reporter series · HS 8486",
      publisher: "United Nations Statistics Division",
      sourceClass: "trade-data",
      evidenceRole: "context",
      canonicalUrl: "https://uncomtrade.org/docs/un-comtrade-api/",
      retrievedAt: "2026-07-21",
      datasetVintage: "2024-01 through 2025-12 public-preview extraction",
      revisionPolicy:
        "UN Comtrade exposes only the latest version of a dataset; later revisions can replace previously retrieved values.",
      language: "en",
      translationStatus: "original-english",
      recordId: "comtrade-842-156-8486-x-2024-2025",
      artifact: {
        path: "public/data/us-china-hs8486-2024-2025.csv",
        sha256:
          "b10581d98a918ee41b3f96ef7e3a3fc8c21f335f7cdefda701c54014baffaa00",
      },
      query: {
        endpoint: "https://comtradeapi.un.org/public/v1/preview/C/M/HS",
        parameters: {
          reporterCode: "842",
          partnerCode: "156",
          cmdCode: "8486",
          flowCode: "X",
          maxRecords: "500",
        },
        periods: [
          "202401",
          "202402",
          "202403",
          "202404",
          "202405",
          "202406",
          "202407",
          "202408",
          "202409",
          "202410",
          "202411",
          "202412",
          "202501",
          "202502",
          "202503",
          "202504",
          "202505",
          "202506",
          "202507",
          "202508",
          "202509",
          "202510",
          "202511",
          "202512",
        ],
      },
      notes:
        "All 24 normalized values were rechecked against one-period official preview requests on July 21, 2026. Responses were aggregate and not directly reported; the series is contextual and is not a substitute for a keyed Census extraction.",
    },
    {
      id: "source-sec-acmr-2025",
      label: "ACM Research 2025 Form 10-K",
      publisher: "US Securities and Exchange Commission",
      sourceClass: "filing",
      evidenceRole: "supporting",
      canonicalUrl:
        "https://www.sec.gov/Archives/edgar/data/1680062/000162828026013231/acmr-20251231.htm",
      publishedAt: "2026-03-02",
      retrievedAt: "2026-07-21",
      datasetVintage: "Fiscal year ended December 31, 2025",
      language: "en",
      translationStatus: "original-english",
      recordId: "sec-acmr-2025-10k",
      notes:
        "Company-reported evidence that ACM Shanghai and ACM Korea were added, procurement was affected, and business practices changed. It is not independent observation of operational impact.",
    },
  ],
  relations: [
    {
      id: "relation-regulatory-reach",
      from: "place-washington-dc",
      to: "place-shanghai",
      label: "Regulatory reach",
      kind: "regulatory-reach",
      sourceIds: [
        "source-bis-announcement",
        "source-federal-register-entity-rule",
      ],
    },
  ],
  places: [
    {
      id: "place-washington-dc",
      label: "Washington, D.C.",
      coordinates: [-77.0369, 38.9072],
      precision: "city",
      role: "Rulemaking and publication",
      sourceIds: [
        "source-bis-announcement",
        "source-federal-register-sme-rule",
        "source-federal-register-entity-rule",
      ],
    },
    {
      id: "place-shanghai",
      label: "Shanghai",
      coordinates: [121.4737, 31.2304],
      precision: "city",
      role: "ACM Shanghai · listed operating subsidiary",
      sourceIds: [
        "source-federal-register-entity-rule",
        "source-sec-acmr-2025",
      ],
    },
  ],
  events: [
    {
      id: "event-package-announced",
      date: "2024-12-02",
      stage: "announcement",
      evidenceStatus: "officiallyAnnounced",
      title: "BIS announces the control package",
      detail:
        "The announcement describes new equipment, software, HBM, end-use, and Entity List measures.",
      sourceIds: ["source-bis-announcement"],
      placeIds: ["place-washington-dc"],
      chainSlugs: ["rule-to-reach", "reach-to-trade"],
    },
    {
      id: "event-rule-published",
      date: "2024-12-05",
      stage: "publication",
      evidenceStatus: "officiallyAnnounced",
      title: "The companion rules enter the Federal Register",
      detail:
        "The interim SME rule and final Entity List rule provide separate controlling records for the package.",
      sourceIds: [
        "source-federal-register-sme-rule",
        "source-federal-register-entity-rule",
      ],
      placeIds: ["place-washington-dc"],
      chainSlugs: ["rule-to-reach", "reach-to-trade"],
    },
    {
      id: "event-compliance-date",
      date: "2024-12-31",
      stage: "implementation",
      evidenceStatus: "implemented",
      title: "FN5-linked compliance date arrives",
      detail:
        "December 31 applies to the amendatory instructions and Entity List requirements linked to Footnote 5—not every addition to the Entity List.",
      sourceIds: [
        "source-federal-register-sme-rule",
        "source-federal-register-entity-rule",
      ],
      placeIds: ["place-washington-dc", "place-shanghai"],
      chainSlugs: ["rule-to-reach", "reach-to-trade"],
    },
    {
      id: "event-company-disclosure",
      date: "2026-03-02",
      stage: "observation",
      evidenceStatus: "reported",
      title: "ACM Research records continuing listing exposure",
      detail:
        "The 2025 filing identifies ACM Shanghai and ACM Korea among the additions and describes continuing operational exposure in mainland China and Korea.",
      sourceIds: ["source-sec-acmr-2025"],
      placeIds: ["place-shanghai"],
      chainSlugs: ["exposure-to-response"],
    },
  ],
  chains: [
    {
      id: "chain-rule-to-reach",
      slug: "rule-to-reach",
      eyebrow: "Policy lifecycle",
      title: "From rule text to compliance",
      summary:
        "Follow the package from the announcement through its defined scope, named parties, and compliance date.",
      steps: [
        {
          id: "step-rule-announcement",
          code: "RULE",
          kind: "rule",
          label: "December package",
          detail:
            "BIS announces the coordinated semiconductor-control package.",
          date: "2024-12-02",
          evidenceStatus: "officiallyAnnounced",
          sourceIds: ["source-bis-announcement", "source-mofcom-response"],
          placeIds: ["place-washington-dc"],
          eventIds: ["event-package-announced"],
          relationIds: [],
          seriesIds: [],
        },
        {
          id: "step-rule-scope",
          code: "SCOPE",
          kind: "scope",
          label: "24 equipment types + 3 software tools",
          detail: "The announcement also covers HBM and related end-use rules.",
          evidenceStatus: "officiallyAnnounced",
          sourceIds: [
            "source-bis-announcement",
            "source-federal-register-sme-rule",
          ],
          placeIds: ["place-washington-dc"],
          eventIds: ["event-rule-published"],
          relationIds: [],
          seriesIds: [],
        },
        {
          id: "step-rule-entities",
          code: "ENTITIES",
          kind: "entity",
          label: "140 additions + 14 modifications",
          detail:
            "The official record, not the screening helper, controls each entry.",
          evidenceStatus: "implemented",
          sourceIds: [
            "source-federal-register-entity-rule",
            "source-trade-csl",
          ],
          placeIds: ["place-washington-dc", "place-shanghai"],
          eventIds: ["event-rule-published"],
          relationIds: ["relation-regulatory-reach"],
          seriesIds: [],
        },
        {
          id: "step-rule-compliance",
          code: "DATE",
          kind: "date",
          label: "December 31 limited compliance",
          detail:
            "The specified FN5, FDP, HBM, and linked Entity List requirements reach their delayed compliance date.",
          date: "2024-12-31",
          evidenceStatus: "implemented",
          sourceIds: [
            "source-federal-register-sme-rule",
            "source-federal-register-entity-rule",
          ],
          placeIds: ["place-washington-dc", "place-shanghai"],
          eventIds: ["event-compliance-date"],
          relationIds: ["relation-regulatory-reach"],
          seriesIds: [],
        },
      ],
      conclusion:
        "The legal sequence is established: announcement, published rule, listed parties, and compliance date can be traced to primary records.",
      caveat:
        "Legal reach does not by itself show the magnitude or effectiveness of the economic outcome.",
      evidenceStatus: "implemented",
    },
    {
      id: "chain-reach-to-trade",
      slug: "reach-to-trade",
      eyebrow: "Measured flow",
      title: "From listed parties to trade movement",
      summary:
        "Connect the official list to an equipment-trade series without presenting temporal alignment as proof of causation.",
      steps: [
        {
          id: "step-trade-list",
          code: "LIST",
          kind: "entity",
          label: "Named entities",
          detail:
            "The Federal Register establishes the affected legal parties.",
          date: "2024-12-05",
          evidenceStatus: "implemented",
          sourceIds: ["source-federal-register-entity-rule"],
          placeIds: ["place-washington-dc", "place-shanghai"],
          eventIds: ["event-rule-published"],
          relationIds: ["relation-regulatory-reach"],
          seriesIds: [],
        },
        {
          id: "step-trade-places",
          code: "PLACES",
          kind: "location",
          label: "Documented regulatory reach",
          detail:
            "The local diagram connects the rulemaking record to a named Shanghai entity; it does not depict a shipment route or commercial relationship.",
          evidenceStatus: "implemented",
          sourceIds: ["source-federal-register-entity-rule"],
          placeIds: ["place-washington-dc", "place-shanghai"],
          eventIds: ["event-rule-published"],
          relationIds: ["relation-regulatory-reach"],
          seriesIds: [],
        },
        {
          id: "step-trade-flow",
          code: "FLOW",
          kind: "trade",
          label: "HS 8486 monthly exports",
          detail:
            "The UN Comtrade US-reporter series provides broad equipment-trade context.",
          evidenceStatus: "reported",
          sourceIds: ["source-census-hs-contract", "source-un-comtrade-hs"],
          placeIds: ["place-washington-dc", "place-shanghai"],
          eventIds: ["event-compliance-date"],
          relationIds: ["relation-regulatory-reach"],
          seriesIds: ["series-us-china-hs8486"],
        },
        {
          id: "step-trade-caveat",
          code: "CAVEAT",
          kind: "caveat",
          label: "Correlation, not attribution",
          detail:
            "Commodity scope, timing, licensing, and annual revisions limit inference.",
          evidenceStatus: "contested",
          sourceIds: ["source-census-hs-contract", "source-un-comtrade-hs"],
          placeIds: [],
          eventIds: [],
          relationIds: [],
          seriesIds: [],
        },
      ],
      conclusion:
        "The pinned series makes a post-rule change visible and testable as context.",
      caveat:
        "The series is broad, estimated in the public preview, and cannot isolate the rule from demand, licensing, or classification effects.",
      evidenceStatus: "contested",
    },
    {
      id: "chain-exposure-to-response",
      slug: "exposure-to-response",
      eyebrow: "Corporate disclosure",
      title: "From affected company to unresolved effect",
      summary:
        "Separate what a listed company disclosed from what independent evidence can establish about outcomes.",
      steps: [
        {
          id: "step-company-identity",
          code: "COMPANY",
          kind: "entity",
          label: "ACM Shanghai and ACM Korea",
          detail:
            "ACM Research identifies both subsidiaries among the additions.",
          date: "2024-12-02",
          evidenceStatus: "reported",
          sourceIds: ["source-sec-acmr-2025"],
          placeIds: ["place-shanghai"],
          eventIds: ["event-company-disclosure"],
          relationIds: [],
          seriesIds: [],
        },
        {
          id: "step-company-disclosure",
          code: "DISCLOSURE",
          kind: "disclosure",
          label: "Continuing operational exposure",
          detail:
            "The filing describes continuing mainland China and Korea operational exposure.",
          date: "2026-03-02",
          evidenceStatus: "reported",
          sourceIds: ["source-sec-acmr-2025"],
          placeIds: ["place-shanghai"],
          eventIds: ["event-company-disclosure"],
          relationIds: [],
          seriesIds: [],
        },
        {
          id: "step-company-effect",
          code: "EFFECT",
          kind: "effect",
          label: "Company-reported response",
          detail:
            "This is attributed disclosure, not independent confirmation.",
          evidenceStatus: "reported",
          sourceIds: ["source-sec-acmr-2025"],
          placeIds: ["place-shanghai"],
          eventIds: ["event-company-disclosure"],
          relationIds: [],
          seriesIds: [],
        },
        {
          id: "step-company-question",
          code: "QUESTION",
          kind: "question",
          label: "What changed in operations?",
          detail:
            "Licensing outcomes and independently measured production effects remain open.",
          evidenceStatus: "contested",
          sourceIds: [
            "source-federal-register-entity-rule",
            "source-sec-acmr-2025",
          ],
          placeIds: ["place-shanghai"],
          eventIds: [],
          relationIds: [],
          seriesIds: [],
        },
      ],
      conclusion:
        "The filing proves that the company disclosed exposure and named affected subsidiaries.",
      caveat:
        "It does not independently prove the size, duration, or cause of an operating effect.",
      evidenceStatus: "reported",
    },
  ],
  series: [
    {
      id: "series-us-china-hs8486",
      slug: "us-china-hs8486",
      title: "UN Comtrade preview: US reporter HS 8486 exports to China",
      description:
        "Monthly value of machines and apparatus used principally in semiconductor and related manufacturing, shown in nominal US dollars.",
      unit: "usd",
      frequency: "monthly",
      methodology:
        "Pinned from UN Comtrade public-preview records for reporter 842, partner 156, export flow X, and HS 8486. The preview marks these aggregate observations as estimated. Census ALL_VAL_MO remains the preferred US-side series but required a personal API key on retrieval.",
      sourceIds: ["source-census-hs-contract", "source-un-comtrade-hs"],
      downloadPath: "/data/us-china-hs8486-2024-2025.csv",
      observations: [
        ["2024-01", 511790292],
        ["2024-02", 226397379],
        ["2024-03", 435264392],
        ["2024-04", 511595149],
        ["2024-05", 289535825],
        ["2024-06", 338993101],
        ["2024-07", 377236164],
        ["2024-08", 299242758],
        ["2024-09", 386938886],
        ["2024-10", 279046480],
        ["2024-11", 218086360],
        ["2024-12", 296282990],
        ["2025-01", 329813603],
        ["2025-02", 126430084],
        ["2025-03", 232033453],
        ["2025-04", 193011625],
        ["2025-05", 225089608],
        ["2025-06", 321873823],
        ["2025-07", 301490611],
        ["2025-08", 144754061],
        ["2025-09", 81501209],
        ["2025-10", 136975784],
        ["2025-11", 59579342],
        ["2025-12", 126059790],
      ].map(([month, value]) => ({
        month,
        value,
        sourceIds: ["source-un-comtrade-hs"],
        estimated: true,
      })),
      annotations: [
        {
          month: "2024-12",
          label: "Control package announced",
          eventId: "event-package-announced",
        },
      ],
    },
  ],
};

const cultureRelease = {
  slug: "rural-creator-platform-chain",
  version: "2026.07.22-1",
  title: "The rural creator platform chain",
  summary:
    "A source-led atlas of how pastoral and factory-life images moved through creator management, short-video distribution, and cross-border commerce—and how later algorithm rules defined platform responsibilities.",
  methodology:
    "This release promotes only source-read leads into its public ledger. Reporting supports attributed observations and the two drawn commercial relationships; the translated rules support only their stated scope, user protections, and effective date. No review-stage Dispatch record is linked or exposed, and no audience count is treated as a durable dataset.",
  publishedAt: "2026-07-22",
  retrievedAt: "2026-07-22",
  evidenceThrough: "2022-03-01",
  editorialStatus: "published",
  provenance: "prototype",
  reviewState: "source-snapshot",
  relatedDispatchIds: [],
  sources: [
    {
      id: "source-li-ziqi-platform-economy",
      label: "Li Ziqi's rural fantasy and the platform economy behind it",
      publisher: "Rest of World",
      sourceClass: "analysis",
      evidenceRole: "supporting",
      canonicalUrl:
        "https://restofworld.org/2021/tiktok-china-influencer-liziqi/",
      publishedAt: "2021-11-01",
      retrievedAt: "2026-07-22",
      datasetVintage: "Article as retrieved July 22, 2026",
      language: "en",
      translationStatus: "original-english",
      recordId: "restofworld-2021-li-ziqi",
      sourceLeadId: "lead-2021-li-ziqi",
      notes:
        "A reported essay and attributed interpretation. It supports Li's rural Mianyang setting, the Hangzhou Weinian management relationship, the described commerce operation, and the 2021 dispute; its arguments about fantasy, politics, and freedom remain the author's analysis.",
    },
    {
      id: "source-factory-tiktok",
      label: "The Chinese content farms behind Factory TikTok",
      publisher: "Rest of World",
      sourceClass: "reporting",
      evidenceRole: "supporting",
      canonicalUrl:
        "https://restofworld.org/2021/the-chinese-content-farms-behind-factory-tiktok/",
      publishedAt: "2021-06-24",
      retrievedAt: "2026-07-22",
      datasetVintage: "Article as retrieved July 22, 2026",
      language: "en",
      translationStatus: "original-english",
      recordId: "restofworld-2021-factory-tiktok",
      sourceLeadId: "lead-2021-factory-tiktok",
      notes:
        "Reported observation and an attributed interview with a Bioa Mall spokesperson. It supports the Hubei-based account operation, factory-site filming, and the spokesperson's statement that the largest customer base was in North America, especially the United States; the account and view counts are period figures, not a maintained series.",
    },
    {
      id: "source-algorithm-provisions-translation",
      label: "Algorithmic Recommendation Management Provisions · translation",
      publisher: "DigiChina",
      sourceClass: "legal-record",
      evidenceRole: "supporting",
      canonicalUrl:
        "https://digichina.stanford.edu/work/translation-internet-information-service-algorithmic-recommendation-management-provisions-effective-march-1-2022/",
      publishedAt: "2022-01-10",
      retrievedAt: "2026-07-22",
      datasetVintage: "Final-version translation corrected February 28, 2022",
      revisionPolicy:
        "DigiChina records a February 28, 2022 correction to the translated effective year.",
      language: "zh/en",
      translationStatus: "bilingual",
      recordId: "digichina-2022-algorithm-provisions",
      sourceLeadId: "lead-2022-algorithm-rules",
      notes:
        "A reviewed English translation presented with the Chinese text. It supports the provisions' mainland scope, disclosure and opt-out duties, complaint channels, and March 1, 2022 effective date. The Chinese original controls legal interpretation.",
    },
  ],
  relations: [
    {
      id: "relation-creator-management",
      from: "place-mianyang",
      to: "place-hangzhou",
      label: "Creator management and brand operations",
      kind: "commercial-management",
      sourceIds: ["source-li-ziqi-platform-economy"],
    },
    {
      id: "relation-factory-audience",
      from: "place-hubei",
      to: "place-united-states",
      label: "Reported largest customer market",
      kind: "audience-reach",
      sourceIds: ["source-factory-tiktok"],
    },
  ],
  places: [
    {
      id: "place-mianyang",
      label: "Mianyang, Sichuan",
      coordinates: [104.7417, 31.464],
      precision: "city",
      role: "Li Ziqi's reported rural home and production setting.",
      sourceIds: ["source-li-ziqi-platform-economy"],
    },
    {
      id: "place-hangzhou",
      label: "Hangzhou",
      coordinates: [120.1551, 30.2741],
      precision: "city",
      role: "Reported headquarters of Hangzhou Weinian, the agency managing Li's social campaigns and food brand.",
      sourceIds: ["source-li-ziqi-platform-economy"],
    },
    {
      id: "place-hubei",
      label: "Hubei province",
      coordinates: [112.3, 30.98],
      precision: "region",
      role: "Reported office base of the Bioa Mall team described in the Factory TikTok investigation.",
      sourceIds: ["source-factory-tiktok"],
    },
    {
      id: "place-united-states",
      label: "United States",
      coordinates: [-98.5795, 39.8283],
      precision: "country",
      role: "Country specifically named within the spokesperson's description of Bioa Mall's largest North American customer base.",
      sourceIds: ["source-factory-tiktok"],
    },
  ],
  events: [
    {
      id: "event-factory-report-published",
      date: "2021-06-24",
      stage: "observation",
      evidenceStatus: "reported",
      title: "Factory TikTok investigation is published",
      detail:
        "The report traces selected factory-video accounts to coordinated e-commerce marketing and an attributed Hubei-based operation.",
      sourceIds: ["source-factory-tiktok"],
      placeIds: ["place-hubei", "place-united-states"],
      chainSlugs: ["factory-floor-to-customer"],
    },
    {
      id: "event-li-report-published",
      date: "2021-11-01",
      stage: "observation",
      evidenceStatus: "reported",
      title: "Li Ziqi platform-economy essay is published",
      detail:
        "The essay connects the pastoral video image to a managed brand, e-commerce products, rural-policy rhetoric, and a public dispute with Hangzhou Weinian.",
      sourceIds: ["source-li-ziqi-platform-economy"],
      placeIds: ["place-mianyang", "place-hangzhou"],
      chainSlugs: ["pastoral-image-to-managed-brand"],
    },
    {
      id: "event-algorithm-translation-published",
      date: "2022-01-10",
      stage: "publication",
      evidenceStatus: "officiallyAnnounced",
      title: "Final-version algorithm provisions translation is published",
      detail:
        "DigiChina publishes its English translation of the final rules and identifies the Chinese-language original.",
      sourceIds: ["source-algorithm-provisions-translation"],
      placeIds: [],
      chainSlugs: ["recommendation-to-user-rights"],
    },
    {
      id: "event-algorithm-rules-effective",
      date: "2022-03-01",
      stage: "implementation",
      evidenceStatus: "implemented",
      title: "Algorithm provisions take effect",
      detail:
        "Article 35 sets March 1, 2022 as the effective date for the provisions applying to algorithmic recommendation services in mainland China.",
      sourceIds: ["source-algorithm-provisions-translation"],
      placeIds: [],
      chainSlugs: ["recommendation-to-user-rights"],
    },
  ],
  chains: [
    {
      id: "chain-pastoral-image-to-managed-brand",
      slug: "pastoral-image-to-managed-brand",
      eyebrow: "Creator economy",
      title: "From pastoral image to managed brand",
      summary:
        "Follow one reported creator case from its rural setting to platform audiences, agency management, and a public dispute over the business.",
      steps: [
        {
          id: "step-rural-setting",
          code: "HOME",
          kind: "location",
          label: "A rural Mianyang setting",
          detail:
            "The essay locates Li Ziqi's home and video setting in rural Mianyang, Sichuan, after her return from city work.",
          evidenceStatus: "reported",
          sourceIds: ["source-li-ziqi-platform-economy"],
          placeIds: ["place-mianyang"],
          eventIds: ["event-li-report-published"],
          relationIds: [],
          seriesIds: [],
        },
        {
          id: "step-pastoral-audience",
          code: "IMAGE",
          kind: "effect",
          label: "Pastoral videos meet global audiences",
          detail:
            "The article reports audiences across Douyin and YouTube and describes the videos as an escape from high-pressure, screen-centered life.",
          evidenceStatus: "reported",
          sourceIds: ["source-li-ziqi-platform-economy"],
          placeIds: ["place-mianyang"],
          eventIds: ["event-li-report-published"],
          relationIds: [],
          seriesIds: [],
        },
        {
          id: "step-managed-brand",
          code: "FIRM",
          kind: "entity",
          label: "Management and commerce sit behind the image",
          detail:
            "Rest of World reports that Hangzhou Weinian managed Li's social campaigns and food brand while brand products were sold through e-commerce.",
          evidenceStatus: "reported",
          sourceIds: ["source-li-ziqi-platform-economy"],
          placeIds: ["place-mianyang", "place-hangzhou"],
          eventIds: ["event-li-report-published"],
          relationIds: ["relation-creator-management"],
          seriesIds: [],
        },
        {
          id: "step-public-dispute",
          code: "BREAK",
          kind: "disclosure",
          label: "The management relationship becomes a dispute",
          detail:
            "The article records Li's 2021 hiatus, public criticism of the influencer economy, and lawsuit against Hangzhou Weinian.",
          date: "2021-11-01",
          evidenceStatus: "reported",
          sourceIds: ["source-li-ziqi-platform-economy"],
          placeIds: ["place-mianyang", "place-hangzhou"],
          eventIds: ["event-li-report-published"],
          relationIds: ["relation-creator-management"],
          seriesIds: [],
        },
      ],
      conclusion:
        "The reviewed article documents a commercial-management layer connecting a rural creator image to an urban agency and e-commerce operation.",
      caveat:
        "One essay cannot measure the broader rural-creator economy, adjudicate the parties' dispute, or establish how representative Li Ziqi was of other creators.",
      evidenceStatus: "reported",
    },
    {
      id: "chain-factory-floor-to-customer",
      slug: "factory-floor-to-customer",
      eyebrow: "Everyday commerce",
      title: "From factory floor to overseas customer",
      summary:
        "Trace a reported account network that repackaged manufacturing footage as cross-border short-video marketing.",
      steps: [
        {
          id: "step-factory-footage",
          code: "FLOOR",
          kind: "observation",
          label: "Manufacturing becomes short-form footage",
          detail:
            "The investigation describes factory processes filmed as visually absorbing clips, often without clear company or location information.",
          date: "2021-06-24",
          evidenceStatus: "reported",
          sourceIds: ["source-factory-tiktok"],
          placeIds: [],
          eventIds: ["event-factory-report-published"],
          relationIds: [],
          seriesIds: [],
        },
        {
          id: "step-account-network",
          code: "NETWORK",
          kind: "entity",
          label: "One team operates many accounts",
          detail:
            "A Bioa Mall spokesperson told Rest of World that a 30-person team operated nearly 200 TikTok accounts at a time.",
          evidenceStatus: "reported",
          sourceIds: ["source-factory-tiktok"],
          placeIds: ["place-hubei"],
          eventIds: ["event-factory-report-published"],
          relationIds: [],
          seriesIds: [],
        },
        {
          id: "step-filming-operation",
          code: "SHOOT",
          kind: "effect",
          label: "Video crews connect accounts to factories",
          detail:
            "The same spokesperson said a small in-house video team was dispatched to factory sites to film assembly-line footage, reviews, and demonstrations.",
          evidenceStatus: "reported",
          sourceIds: ["source-factory-tiktok"],
          placeIds: ["place-hubei"],
          eventIds: ["event-factory-report-published"],
          relationIds: [],
          seriesIds: [],
        },
        {
          id: "step-overseas-customer",
          code: "MARKET",
          kind: "trade",
          label: "The reported customer base reaches the United States",
          detail:
            "The spokesperson described North America—specifically the United States—as the operation's largest customer base.",
          evidenceStatus: "reported",
          sourceIds: ["source-factory-tiktok"],
          placeIds: ["place-hubei", "place-united-states"],
          eventIds: ["event-factory-report-published"],
          relationIds: ["relation-factory-audience"],
          seriesIds: [],
        },
      ],
      conclusion:
        "The investigation documents at least one coordinated Hubei-based operation using factory footage and many TikTok accounts to market goods to overseas customers.",
      caveat:
        "The spokesperson's figures are attributed period claims, and the case does not establish the size, geography, or labor conditions of Factory TikTok as a whole.",
      evidenceStatus: "reported",
    },
    {
      id: "chain-recommendation-to-user-rights",
      slug: "recommendation-to-user-rights",
      eyebrow: "Platform rules",
      title: "From recommendation systems to stated user rights",
      summary:
        "Read the later algorithm provisions as a separate legal layer around platform recommendation—not as proof of what caused either reported creator case.",
      steps: [
        {
          id: "step-rule-scope",
          code: "SCOPE",
          kind: "scope",
          label: "Recommendation is defined broadly",
          detail:
            "The translation says the provisions cover generative or synthetic, personalized recommendation, ranking, search-filtering, and dispatch or decision-making technologies used for internet information services in mainland China.",
          date: "2022-01-10",
          evidenceStatus: "officiallyAnnounced",
          sourceIds: ["source-algorithm-provisions-translation"],
          placeIds: [],
          eventIds: ["event-algorithm-translation-published"],
          relationIds: [],
          seriesIds: [],
        },
        {
          id: "step-rule-disclosure",
          code: "NOTICE",
          kind: "rule",
          label: "Providers must disclose basic mechanisms",
          detail:
            "Articles 16 and 17 require notice that algorithmic recommendation is used, disclosure of basic principles, and an option to disable personalized recommendation or receive a non-personalized alternative.",
          evidenceStatus: "officiallyAnnounced",
          sourceIds: ["source-algorithm-provisions-translation"],
          placeIds: [],
          eventIds: ["event-algorithm-translation-published"],
          relationIds: [],
          seriesIds: [],
        },
        {
          id: "step-rule-complaints",
          code: "APPEAL",
          kind: "rule",
          label: "Complaint channels are required",
          detail:
            "Article 22 requires convenient complaint and reporting access points, defined handling workflows, and feedback time periods.",
          evidenceStatus: "officiallyAnnounced",
          sourceIds: ["source-algorithm-provisions-translation"],
          placeIds: [],
          eventIds: ["event-algorithm-translation-published"],
          relationIds: [],
          seriesIds: [],
        },
        {
          id: "step-rule-effective",
          code: "DATE",
          kind: "date",
          label: "The provisions take effect",
          detail:
            "Article 35 states that the final provisions take effect on March 1, 2022.",
          date: "2022-03-01",
          evidenceStatus: "implemented",
          sourceIds: ["source-algorithm-provisions-translation"],
          placeIds: [],
          eventIds: ["event-algorithm-rules-effective"],
          relationIds: [],
          seriesIds: [],
        },
      ],
      conclusion:
        "The translated final text documents formal duties around recommendation disclosure, user choice, complaints, and oversight from March 2022.",
      caveat:
        "The rules postdate the two 2021 reports and do not establish compliance, enforcement outcomes, or causation in either creator case; the Chinese original controls legal interpretation.",
      evidenceStatus: "implemented",
    },
  ],
  series: [],
};

const openModelRelease = {
  slug: "open-model-release-ledger",
  version: "2026.07.22-1",
  title: "The open-model release ledger",
  summary:
    "A source-led atlas separating model announcements, API access, downloadable weights, licenses, technical disclosure, and independent evaluation across the recent US–China open-weight cycle.",
  methodology:
    "This release uses only source-read first-party records, technical papers, and a reviewed annotated translation. A company can establish what it released or promised, but its benchmark, cost, safety, and strategy claims remain attributed. The supplied sourcebook guides the questions; it is not itself treated as evidence, and no review-stage Dispatch or Hacker News commentary is exposed.",
  publishedAt: "2026-07-22",
  retrievedAt: "2026-07-22",
  evidenceThrough: "2026-07-18",
  editorialStatus: "published",
  provenance: "prototype",
  reviewState: "source-snapshot",
  relatedDispatchIds: [],
  sources: [
    {
      id: "source-llama-2-release",
      label: "Meta and Microsoft introduce Llama 2",
      publisher: "Meta AI",
      sourceClass: "product-release",
      evidenceRole: "supporting",
      canonicalUrl: "https://ai.meta.com/blog/llama-2/",
      publishedAt: "2023-07-18",
      retrievedAt: "2026-07-22",
      datasetVintage: "Release post as retrieved July 22, 2026",
      language: "en",
      translationStatus: "original-english",
      recordId: "meta-2023-llama-2-release",
      sourceLeadId: "lead-2023-meta-llama-2",
      notes:
        "First-party release record for model weights, starting code, research and commercial availability, and distribution partners. Meta calls Llama 2 open source; the Atlas uses the narrower open-weight description because the custom license and acceptable-use policy impose conditions.",
    },
    {
      id: "source-deepseek-v2-paper",
      label: "DeepSeek-V2 technical paper",
      publisher: "DeepSeek AI",
      sourceClass: "technical-paper",
      evidenceRole: "supporting",
      canonicalUrl: "https://arxiv.org/abs/2405.04434",
      publishedAt: "2024-05-07",
      retrievedAt: "2026-07-22",
      datasetVintage: "arXiv v5 dated June 19, 2024",
      revisionPolicy:
        "arXiv versions may change; the source page identifies v1 through v5 and the current version.",
      language: "en",
      translationStatus: "original-english",
      recordId: "arxiv-2405-04434-v5",
      sourceLeadId: "lead-2024-deepseek-v2",
      notes:
        "Primary technical disclosure for the 236B-parameter mixture-of-experts design, 21B activated parameters, MLA, DeepSeekMoE, and vendor-reported efficiency comparisons. Architecture and experiment descriptions are direct evidence; comparative performance and cost figures remain author claims until independently reproduced.",
    },
    {
      id: "source-qwen2-release",
      label: "Hello Qwen2",
      publisher: "Qwen Team",
      sourceClass: "product-release",
      evidenceRole: "supporting",
      canonicalUrl: "https://qwenlm.github.io/blog/qwen2/",
      publishedAt: "2024-06-07",
      retrievedAt: "2026-07-22",
      datasetVintage: "Release post as retrieved July 22, 2026",
      language: "en/zh",
      translationStatus: "bilingual",
      recordId: "qwen-2024-qwen2-release",
      sourceLeadId: "lead-2024-qwen2-release",
      notes:
        "First-party release record linking five model sizes to GitHub, Hugging Face, and ModelScope. Those artifact links support availability; the benchmark tables and qualitative performance statements remain vendor evaluations.",
    },
    {
      id: "source-llama-3-1-release",
      label: "Introducing Llama 3.1",
      publisher: "Meta AI",
      sourceClass: "product-release",
      evidenceRole: "supporting",
      canonicalUrl: "https://ai.meta.com/blog/meta-llama-3-1/",
      publishedAt: "2024-07-23",
      retrievedAt: "2026-07-22",
      datasetVintage: "Release post as retrieved July 22, 2026",
      language: "en",
      translationStatus: "original-english",
      recordId: "meta-2024-llama-3-1-release",
      sourceLeadId: "lead-2024-meta-llama-3-1",
      notes:
        "First-party record for downloadable 8B, 70B, and 405B models, a license change permitting model outputs to improve other models, partner availability, and supporting tools. Capability, cost, safety, and download-total statements remain Meta claims unless separately corroborated.",
    },
    {
      id: "source-deepseek-founder-interview",
      label: "DeepSeek founder interview · annotated translation",
      publisher: "ChinaTalk",
      sourceClass: "analysis",
      evidenceRole: "context",
      canonicalUrl:
        "https://www.chinatalk.media/p/deepseek-ceo-interview-with-chinas",
      publishedAt: "2024-11-27",
      retrievedAt: "2026-07-22",
      datasetVintage:
        "Annotated translation of a July 2024 36Kr/Waves interview",
      language: "zh/en",
      translationStatus: "bilingual",
      recordId: "chinatalk-2024-liang-wenfeng-interview",
      sourceLeadId: "lead-2024-chinatalk-deepseek-interview",
      notes:
        "A reviewed annotated translation preserving a first-person account of DeepSeek's research, pricing, recruiting, and open-release strategy. Liang Wenfeng's explanations establish his stated position, not independently verified company motives, economics, or industry-wide behavior; translator annotations are separate commentary.",
    },
    {
      id: "source-kimi-k3-launch",
      label: "Kimi K3 launch",
      publisher: "Moonshot AI",
      sourceClass: "product-release",
      evidenceRole: "supporting",
      canonicalUrl: "https://www.kimi.com/blog/kimi-k3",
      publishedAt: "2026-07-16",
      retrievedAt: "2026-07-22",
      datasetVintage: "Launch post before the promised July 27 follow-up",
      revisionPolicy:
        "Recheck on or after July 27, 2026 for weights, model card, license, inference code, checksums, and the technical report.",
      language: "en",
      translationStatus: "original-english",
      recordId: "moonshot-2026-kimi-k3-launch-pre-weights",
      sourceLeadId: "lead-2026-kimi-k3",
      notes:
        "Controlling first-party record for product and API availability and the promise to release full weights by July 27 with a technical report. As of this snapshot it does not establish that weights, a license, inference artifacts, or the report have shipped; all performance and economics statements are vendor claims.",
    },
    {
      id: "source-world-ai-keynote",
      label: "Keynote address at the 2026 World AI Conference",
      publisher: "Xinhua / State Council Information Office",
      sourceClass: "policy",
      evidenceRole: "context",
      canonicalUrl:
        "https://english.scio.gov.cn/topnews/2026-07/18/content_118605932.html",
      publishedAt: "2026-07-18",
      retrievedAt: "2026-07-22",
      datasetVintage: "Official English text of the July 17, 2026 address",
      language: "en",
      translationStatus: "original-english",
      recordId: "scio-2026-world-ai-keynote",
      sourceLeadId: "lead-2026-scio-world-ai-keynote",
      notes:
        "Official English record of policy language advocating openness, collaboration, sharing, industrial application, and international governance. It does not establish why an individual lab released a model, what its license permits, or whether a promised artifact shipped.",
    },
  ],
  relations: [],
  places: [],
  events: [
    {
      id: "event-llama-2-release",
      date: "2023-07-18",
      stage: "publication",
      evidenceStatus: "implemented",
      title: "Llama 2 weights and starting code are released",
      detail:
        "Meta announces model weights and starting code for research and most commercial use under its own license and policies.",
      sourceIds: ["source-llama-2-release"],
      placeIds: [],
      chainSlugs: ["precedents-not-nationality", "release-state-not-label"],
    },
    {
      id: "event-deepseek-v2-paper",
      date: "2024-05-07",
      stage: "publication",
      evidenceStatus: "reported",
      title: "DeepSeek-V2 technical paper enters the record",
      detail:
        "The paper documents the model's architecture, training description, and author-reported efficiency and performance results.",
      sourceIds: ["source-deepseek-v2-paper"],
      placeIds: [],
      chainSlugs: ["precedents-not-nationality", "firms-not-one-actor"],
    },
    {
      id: "event-qwen2-release",
      date: "2024-06-07",
      stage: "publication",
      evidenceStatus: "implemented",
      title: "Qwen2 release post links downloadable artifacts",
      detail:
        "The Qwen Team publishes model information and direct links to GitHub, Hugging Face, and ModelScope artifacts.",
      sourceIds: ["source-qwen2-release"],
      placeIds: [],
      chainSlugs: ["precedents-not-nationality", "firms-not-one-actor"],
    },
    {
      id: "event-llama-3-1-release",
      date: "2024-07-23",
      stage: "publication",
      evidenceStatus: "implemented",
      title: "Llama 3.1 expands the release and derivative-use terms",
      detail:
        "Meta publishes downloadable models, partner availability, new system components, and a license change concerning model outputs.",
      sourceIds: ["source-llama-3-1-release"],
      placeIds: [],
      chainSlugs: ["precedents-not-nationality", "release-state-not-label"],
    },
    {
      id: "event-deepseek-interview-translation",
      date: "2024-11-27",
      stage: "observation",
      evidenceStatus: "reported",
      title: "A translated first-person DeepSeek strategy record is published",
      detail:
        "ChinaTalk publishes an annotated translation of Liang Wenfeng's July 2024 interview about research, prices, talent, and open releases.",
      sourceIds: ["source-deepseek-founder-interview"],
      placeIds: [],
      chainSlugs: ["firms-not-one-actor"],
    },
    {
      id: "event-kimi-k3-launch",
      date: "2026-07-16",
      stage: "announcement",
      evidenceStatus: "officiallyAnnounced",
      title: "Kimi K3 launches through products and API",
      detail:
        "Moonshot announces product and API availability while promising full weights and the technical report for a later date.",
      sourceIds: ["source-kimi-k3-launch"],
      placeIds: [],
      chainSlugs: ["release-state-not-label", "firms-not-one-actor"],
    },
    {
      id: "event-world-ai-keynote",
      date: "2026-07-17",
      stage: "announcement",
      evidenceStatus: "officiallyAnnounced",
      title: "Official address advocates open AI collaboration",
      detail:
        "The official English text records national-level policy language one day after the Kimi announcement; temporal proximity does not prove coordination or causation.",
      sourceIds: ["source-world-ai-keynote"],
      placeIds: [],
      chainSlugs: ["firms-not-one-actor"],
    },
  ],
  chains: [
    {
      id: "chain-release-state-not-label",
      slug: "release-state-not-label",
      eyebrow: "Publication gate",
      title: "A release is a stack of separate evidence",
      summary:
        "Use historical completed releases and the current Kimi checkpoint to separate access, artifacts, legal permissions, and technical verification.",
      steps: [
        {
          id: "step-release-announcement",
          code: "CLAIM",
          kind: "announcement",
          label: "A company announces a model and posture",
          detail:
            "A launch page establishes what the issuer said and which products or APIs it made available; it does not independently establish performance or openness.",
          date: "2026-07-16",
          evidenceStatus: "officiallyAnnounced",
          sourceIds: ["source-kimi-k3-launch"],
          placeIds: [],
          eventIds: ["event-kimi-k3-launch"],
          relationIds: [],
          seriesIds: [],
        },
        {
          id: "step-release-access",
          code: "ACCESS",
          kind: "implementation",
          label: "Product or API access can arrive first",
          detail:
            "Kimi K3 was available through Kimi products, Kimi Code, and the API at this checkpoint, while downloadable weights remained a future promise.",
          evidenceStatus: "implemented",
          sourceIds: ["source-kimi-k3-launch"],
          placeIds: [],
          eventIds: ["event-kimi-k3-launch"],
          relationIds: [],
          seriesIds: [],
        },
        {
          id: "step-release-weights-license",
          code: "ARTIFACT",
          kind: "caveat",
          label: "Weights and license require direct artifact evidence",
          detail:
            "Llama 2 and Llama 3.1 show completed weight releases with stated license terms; Kimi's launch instead set July 27 as a future weight-release date.",
          evidenceStatus: "contested",
          sourceIds: [
            "source-llama-2-release",
            "source-llama-3-1-release",
            "source-kimi-k3-launch",
          ],
          placeIds: [],
          eventIds: [
            "event-llama-2-release",
            "event-llama-3-1-release",
            "event-kimi-k3-launch",
          ],
          relationIds: [],
          seriesIds: [],
        },
        {
          id: "step-release-verification",
          code: "VERIFY",
          kind: "question",
          label: "Technical disclosure is not independent evaluation",
          detail:
            "The promised Kimi report, checksums, inference support, reproducible evaluations, and independent safety or workload tests remain separate follow-ups.",
          evidenceStatus: "reported",
          sourceIds: ["source-kimi-k3-launch"],
          placeIds: [],
          eventIds: ["event-kimi-k3-launch"],
          relationIds: [],
          seriesIds: [],
        },
      ],
      conclusion:
        "The record supports saying Kimi K3 had launched through products and API and was announced for a later weight release—not that every open-model artifact was already available.",
      caveat:
        "This snapshot predates July 27. It cannot establish whether Moonshot fulfilled the promise, what the final license permits, or how the downloadable artifact performs.",
      evidenceStatus: "officiallyAnnounced",
    },
    {
      id: "chain-precedents-not-nationality",
      slug: "precedents-not-nationality",
      eyebrow: "Release chronology",
      title: "Open-weight precedents cross national labels",
      summary:
        "Follow a narrow chronology of completed first-party and technical records without turning it into a country-level scoreboard.",
      steps: [
        {
          id: "step-precedent-llama-2",
          code: "LLAMA 2",
          kind: "implementation",
          label: "Meta releases weights and starting code",
          detail:
            "The 2023 post records model weights, starting code, research and commercial availability, and distribution through cloud and model platforms.",
          date: "2023-07-18",
          evidenceStatus: "implemented",
          sourceIds: ["source-llama-2-release"],
          placeIds: [],
          eventIds: ["event-llama-2-release"],
          relationIds: [],
          seriesIds: [],
        },
        {
          id: "step-precedent-deepseek-v2",
          code: "V2 PAPER",
          kind: "disclosure",
          label: "DeepSeek publishes architectural disclosure",
          detail:
            "The DeepSeek-V2 paper documents MLA, sparse mixture-of-experts design, training, and issuer-reported efficiency results.",
          date: "2024-05-07",
          evidenceStatus: "reported",
          sourceIds: ["source-deepseek-v2-paper"],
          placeIds: [],
          eventIds: ["event-deepseek-v2-paper"],
          relationIds: [],
          seriesIds: [],
        },
        {
          id: "step-precedent-qwen2",
          code: "QWEN2",
          kind: "implementation",
          label: "Qwen links multiple model artifacts",
          detail:
            "The Qwen2 post links released model sizes across GitHub, Hugging Face, and ModelScope while keeping its benchmark claims first-party.",
          date: "2024-06-07",
          evidenceStatus: "implemented",
          sourceIds: ["source-qwen2-release"],
          placeIds: [],
          eventIds: ["event-qwen2-release"],
          relationIds: [],
          seriesIds: [],
        },
        {
          id: "step-precedent-llama-3-1",
          code: "LLAMA 3.1",
          kind: "implementation",
          label: "Meta expands models, partners, and derivative rights",
          detail:
            "The Llama 3.1 release combines downloadable models with partner infrastructure, safety tools, and changed terms for using outputs to improve other models.",
          date: "2024-07-23",
          evidenceStatus: "implemented",
          sourceIds: ["source-llama-3-1-release"],
          placeIds: [],
          eventIds: ["event-llama-3-1-release"],
          relationIds: [],
          seriesIds: [],
        },
      ],
      conclusion:
        "The reviewed chronology contains substantial US and Chinese open-weight or technical-release records before the July 2026 debate.",
      caveat:
        "These sources use inconsistent openness language and licenses. Chronology does not measure adoption, reproduce benchmarks, compare legal permissions, or prove a national strategy.",
      evidenceStatus: "implemented",
    },
    {
      id: "chain-firms-not-one-actor",
      slug: "firms-not-one-actor",
      eyebrow: "Interpretation boundary",
      title: "Policy language and company behavior are different records",
      summary:
        "Keep a national policy statement, technical artifacts, a founder's account, and one pending company promise in their proper evidentiary roles.",
      steps: [
        {
          id: "step-firms-policy",
          code: "POLICY",
          kind: "rule",
          label: "Official language favors openness and application",
          detail:
            "The official English address advocates collaboration, sharing, industrial application, and international AI governance.",
          date: "2026-07-17",
          evidenceStatus: "officiallyAnnounced",
          sourceIds: ["source-world-ai-keynote"],
          placeIds: [],
          eventIds: ["event-world-ai-keynote"],
          relationIds: [],
          seriesIds: [],
        },
        {
          id: "step-firms-founder-account",
          code: "MOTIVE",
          kind: "observation",
          label: "A founder gives one lab's explanation",
          detail:
            "Liang Wenfeng describes DeepSeek's emphasis on architectural research, accessible APIs, recruitment, and participation in global innovation.",
          date: "2024-11-27",
          evidenceStatus: "reported",
          sourceIds: ["source-deepseek-founder-interview"],
          placeIds: [],
          eventIds: ["event-deepseek-interview-translation"],
          relationIds: [],
          seriesIds: [],
        },
        {
          id: "step-firms-artifacts",
          code: "RECORD",
          kind: "disclosure",
          label: "Technical and release records show distinct choices",
          detail:
            "DeepSeek's paper emphasizes architecture and efficiency disclosure; Qwen2's release emphasizes a family of linked downloadable artifacts and multilingual coverage.",
          evidenceStatus: "reported",
          sourceIds: ["source-deepseek-v2-paper", "source-qwen2-release"],
          placeIds: [],
          eventIds: ["event-deepseek-v2-paper", "event-qwen2-release"],
          relationIds: [],
          seriesIds: [],
        },
        {
          id: "step-firms-current-limit",
          code: "LIMIT",
          kind: "caveat",
          label: "The newest case remains an unfulfilled checkpoint",
          detail:
            "Moonshot made Kimi K3 available through products and API while deferring full weights and the technical report to July 27.",
          date: "2026-07-16",
          evidenceStatus: "officiallyAnnounced",
          sourceIds: ["source-kimi-k3-launch"],
          placeIds: [],
          eventIds: ["event-kimi-k3-launch"],
          relationIds: [],
          seriesIds: [],
        },
      ],
      conclusion:
        "The sources support multiple overlapping company release strategies within a broader official openness message; they do not support treating China as one model publisher.",
      caveat:
        "A policy speech does not prove firm motive, and founder or vendor statements do not establish industry-wide behavior, market leadership, or durable future openness.",
      evidenceStatus: "reported",
    },
  ],
  series: [],
};

export const atlasReleases: AtlasRelease[] = [
  AtlasReleaseSchema.parse(release),
  AtlasReleaseSchema.parse(cultureRelease),
  AtlasReleaseSchema.parse(openModelRelease),
];

export const publishedAtlasReleases = atlasReleases.filter(
  (item) =>
    item.editorialStatus === "published" || item.editorialStatus === "corrected"
);

export const atlasRelease = publishedAtlasReleases[0];

export function getAtlasRelease(slug: string): AtlasRelease | undefined {
  return publishedAtlasReleases.find((item) => item.slug === slug);
}

export function getAtlasReleaseForDossier(
  dossierSlug: string
): AtlasRelease | undefined {
  return publishedAtlasReleases.find(
    (item) => item.dossierSlug === dossierSlug
  );
}
